### 라이브러리 & 데이터 불러오기

In [ ]:
import pandas as pd

In [ ]:
# 경고 무시
pd.set_option('mode.chained_assignment',  None)

In [ ]:
book_rating = pd.read_csv('왓챠피디아 책 평점.csv')
movie_rating = pd.read_csv('왓챠피디아 영화 평점.csv')

### 영화 평점 전처리

In [ ]:
movie_rating

                user movie movie_ID rating
0      Pznx9j3wJq761    명량  mWzM9D5    2.0
1      8nPvyyWmovYo0    명량  mWzM9D5    1.0
2      DgwxAeQYNxrMj    명량  mWzM9D5    2.5
3      zNM5NrKAQ526j    명량  mWzM9D5    2.0
4      JgAx8QgkOqLbO    명량  mWzM9D5    1.5
...              ...   ...      ...    ...
27554  JgAx89MRDqLbO  블라인드  m5e77oO    3.0
27555  nkPvrQAPJqgar  블라인드  m5e77oO    3.0
27556  a9L5PwKN2vwg8  블라인드  m5e77oO    3.0
27557  24BqEMAnOqrjn  블라인드  m5e77oO    3.0
27558  nkPvrnNdlvgar  블라인드  m5e77oO    2.5

[27559 rows x 4 columns]

In [ ]:
movie_rating[movie_rating['movie']=='스파이']['movie_ID'].unique()

array(['m5rQoaV', 'mW48noW'], dtype=object)

In [ ]:
spy_idx = movie_rating[movie_rating['movie_ID'] == 'm5rQoaV'].index
movie_rating.loc[spy_idx,'movie'] = '스파이(spy)'

In [ ]:
# 영화명 중복 없는지 확인
movie_rating.pivot('user','movie','rating')

movie,#살아있다,007 스카이폴,007 퀀텀 오브 솔러스,1987,1번가의 기적,2012,26년,300,7광구,7급 공무원,...,화려한 휴가,화이 : 괴물을 삼킨 아이,화차,황금나침반,황산벌,황해,효자동 이발사,후궁 : 제왕의 첩,히말라야,히트맨
user,,,,,,,,,,,,,,,,,,,,,
06nkPvrlxgarB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0LzNM5Nox26j7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV08glxzyn,NaN,4.0,3.5,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
17ovV0Br1xzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV0JrLxzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zNM5NzQDn526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzXBQ526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzbLo526j,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzddl526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzlkd526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
movie_rating.to_csv('사용자_영화_평점.csv', index=False)

### 책 데이터 전처리

In [ ]:
book_rating

                 user             book  book_ID  rating
0       8nPvyyWmovYo0    해리 포터와 마법사의 돌  boYDGk4     3.0
1       8nPvyyWmovYo0             파리대왕  bowNK14     3.5
2       8nPvyyWmovYo0          지금 이 순간  boYOaR9     2.5
3       8nPvyyWmovYo0               식객  byzGpdW     4.0
4       8nPvyyWmovYo0            아웃라이어  bolJAN7     3.0
...               ...              ...      ...     ...
349752  17ovVzDWLvzyn          로빈슨 크루소  boO1nW9     4.0
349753  17ovVzDWLvzyn           이기는 습관  b4M5NEd     2.0
349754  17ovVzDWLvzyn  멈추면, 비로소 보이는 것들  byaOv5x     2.5
349755  17ovVzDWLvzyn          우체부 프레드  bydRVNl     1.0
349756  17ovVzDWLvzyn      나의 라임 오렌지나무  byzeJko     5.0

[349757 rows x 4 columns]

In [ ]:
book = pd.read_csv('교보, 서울도서관 100선 문학, 베스트셀러 문학_책소개.csv')
book

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면(30만 부 기념 리커버 에디션),김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽(The One Thing)(리커버 특별판),게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791190382915,생에 감사해,김혜자,시/에세이,NaN,"우리들의 배우 김혜자의 연기, 인생\n“그럼에도 불구하고, 생에 감사해”\n\n한국..."
3,9791161571188,불편한 편의점(벚꽃 에디션),김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
4,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
...,...,...,...,...,...,...
2607,9791189336462,헌책방 기담 수집가 (사연 있는 책을 찾아드립니다. 수수료는 당신 삶의 이야기!),윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
2608,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
2609,9791159257117,클락워크 도깨비 (경성 무한 역동 도깨비불),황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...
2610,9791136748195,비밀 THE TOP SECRET season0 (10),Reiko Shimizu,NaN,8.0,"준이치로부터 마이를 구해낸 히카루, 그리고 히카루를 진심으로 믿고 싶은 아오키."
2611,9788986022476,한그루 열두 가지,박정미,NaN,8.0,도시생활자의 마음밭에 심어보는\n일 년 열두 가지 작물\n\n공방 ‘달실’ 김기란 ...

In [ ]:
# 교보/서울 100선, 베스트셀러 데이터 나누기
kyobo = book[book['분류기호'].isnull()]
seoul = book[book['분야'].isnull()]

### 교보 데이터 처리

In [ ]:
kyobo.drop(kyobo[kyobo['상품명']=='문재인의 위로'].index, inplace=True)
kyobo.reset_index(drop=True, inplace=True)

In [ ]:
kyobo

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면(30만 부 기념 리커버 에디션),김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽(The One Thing)(리커버 특별판),게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791190382915,생에 감사해,김혜자,시/에세이,NaN,"우리들의 배우 김혜자의 연기, 인생\n“그럼에도 불구하고, 생에 감사해”\n\n한국..."
3,9791161571188,불편한 편의점(벚꽃 에디션),김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
4,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
...,...,...,...,...,...,...
634,9791162542569,하루를 48시간으로 사는 마법,이재은,자기계발,NaN,“무심코 허비했던 당신의 하루를 되돌려드립니다!”\n‘방송국 헤르미온느’ 이재은 아...
635,9788972773641,호감 가는 말투에는 비밀이 있다,장신웨,자기계발,NaN,오해는 줄이고 이해는 높이는 말하기를 배우다!\n중국의 최대 포털 사이트 바이두의 ...
636,9791165345204,책들의 부엌 (인사이드 에디션),김지혜,소설,NaN,★★★ 《책들의 부엌》 50쇄 기념 인사이드 에디션 출간 ★★★\n일상에서 벗어나고...
637,9788931011623,사랑의 기술,에리히 프롬,인문,NaN,에리히 프롬의 마지막을 함께한 라이너 풍크 박사의 \n《사랑의 기술》 50주년 기념...
638,9791192237022,고민의 답,글배우,자기계발,NaN,“고민의 답”\n“인생에 답을 모르겠을 때 답을 찾게 해준 책“ 일과 사랑 모든 고...

In [ ]:
# 책 이름 통일하기 (에디션, 특별판 같은 괄호 문장 제거)
kyobo_idx = kyobo[kyobo['상품명'].map(lambda x: '(' in x)].index
kyobo_modi = list(kyobo.loc[kyobo_idx]['상품명'])
kyobo_modi = [book[:book.rindex('(')] for book in kyobo_modi]
kyobo_modi = [book[:book.rindex('(')] if '(' in book else book for book in kyobo_modi]
kyobo.loc[kyobo_idx, '상품명'] = kyobo_modi

In [ ]:
# 책 이름 오른쪽 공백 제거
kyobo['상품명'] = kyobo['상품명'].map(lambda x: x.rstrip())

In [ ]:
# 책 평점 목록
book_rating['book']

0           해리 포터와 마법사의 돌
1                    파리대왕
2                 지금 이 순간
3                      식객
4                   아웃라이어
               ...
349752            로빈슨 크루소
349753             이기는 습관
349754    멈추면, 비로소 보이는 것들
349755            우체부 프레드
349756        나의 라임 오렌지나무
Name: book, Length: 349757, dtype: object

In [ ]:
# 책 평점 목록에 존재하지 않는 책 선택
b_list = kyobo[kyobo['상품명'].map(lambda x: x not in list(book_rating['book']))]

In [ ]:
b_list[160:]

,상품코드,상품명,인물,분야,분류기호,책 소개
589,9791165343996,서울 자가에 대기업 다니는 김 부장 이야기 1: 김부장 편,송희구,자기계발,NaN,2021년 대한민국 직장생활과 부동산에 관한 \n현실을 적나라하게 표현한 하이퍼리얼...
596,9788931557527,부의 품격: 착하게 살아도 성공할 수 있다,양원근,자기계발,NaN,"선의지(善意志), ‘선의’와 실행력‘으로 성공하는 법!\n회사와 삶을 경영하는 데 ..."
602,9791191043761,멘탈을 바꿔야 인생이 바뀐다,박세니,자기계발,NaN,"2022년, 10만 부가 넘게 판매되며 화제를 모았던\n국내 최고 성공심리학 전문가..."
612,9788965137702,유럽 도시 기행 2,유시민,인문,NaN,"유시민의 3년 만에 돌아온 신작,\n《유럽도시기행 2》는 시대의 격랑을 이겨내고 저..."
615,9791164455355,나의 MBTI가 궁금하단 마리몽,김소나,시/에세이,NaN,텀블벅 2000% 달성!\n여러분의 MBTI는 무엇입니까?\n\n혈액형 A형은 소심...
618,9791159095887,벌거벗은 세계사: 사건편,tvn<벌거벗은세계사>제작팀,역사/문화,NaN,이토록 재미있는 세계사라니!\ntvN 〈벌거벗은 세계사〉가 들려준 프레임 밖의 역사...
623,9791197693007,이순신의 바다,황현필,역사/문화,NaN,60만 구독자 1억뷰 조회의 명강의를 책으로 만나다!\n수많은 역사서 제안 러브콜에...
630,9791170400608,너무 잘하려고 애쓰지 마라,나태주,시/에세이,NaN,"“그래도, 그래도 말입니다.\n두 손에 아직도 시가 쥐어져 있으니 이 얼마나 다행한..."
631,9788972773610,컬러애 물들다,밥 햄블리,자기계발,NaN,“최고의 전략은 색이다”\n화려한 컬러의 세계가 들려주는 경이롭고 흥미로운 이야기\...
633,9791192372037,저 별은 모두 당신을 위해 빛나고 있다,손힘찬(오가타 마리토),시/에세이,NaN,“나의 삶은 나를 위해 존재하는 것이다 나의 밤하늘에 자신감이 반짝이기를”\n...
638,9791192237022,고민의 답,글배우,자기계발,NaN,“고민의 답”\n“인생에 답을 모르겠을 때 답을 찾게 해준 책“ 일과 사랑 모든 고...

In [ ]:
# kyobo 데이터 책 이름이랑 왓챠피디아 책 이름 통일하기 (수작업)
kyobo.loc[1, '상품명'] = '원씽 The One Thing'
kyobo.loc[17, '상품명'] = '그릿 GRIT'
kyobo.loc[26, '상품명'] = '지적 대화를 위한 넓고 얕은 지식'
kyobo.loc[31, '상품명'] = '파친코'
kyobo.loc[57, '상품명'] = '지적 대화를 위한 넓고 얕은 지식 : 제로 편'
kyobo.loc[63, '상품명'] = '씽킹 101 : 더 나은 삶을 위한 생각하기 연습'
kyobo.loc[78, '상품명'] = '달러구트 꿈 백화점'
kyobo.loc[100, '상품명'] = '웰씽킹 WEALTHINKING'
kyobo.loc[103, '상품명'] = '데일 카네기 자기관리론'
kyobo.loc[117, '상품명'] = '자소서 바이블'
kyobo.loc[131, '상품명'] = '지적 대화를 위한 넓고 얕은 지식'
kyobo.loc[142, '상품명'] = '효기심의 권력으로 읽는 세계사 : 유럽 편'
kyobo.loc[186, '상품명'] = '디깅 Digging'
kyobo.loc[194, '상품명'] = '벌거벗은 한국사 : 권력편'
kyobo.loc[197, '상품명'] = '역행자 확장판'
kyobo.loc[202, '상품명'] = '시간 연금술사'
kyobo.loc[207, '상품명'] = '벌거벗은 한국사 : 경제편'
kyobo.loc[240, '상품명'] = '꿀벌의 예언'
kyobo.loc[242, '상품명'] = 'CODE 612 누가 어린 왕자를 죽였는가'
kyobo.loc[250, '상품명'] = '상처받지 않는 영혼'
kyobo.loc[254, '상품명'] = '리얼리티 트랜서핑'
kyobo.loc[258, '상품명'] = '소설 보다 : 여름'
kyobo.loc[288, '상품명'] = '고양이'
kyobo.loc[290, '상품명'] = '가면 산장 살인 사건'
kyobo.loc[294, '상품명'] = '골든아워'
kyobo.loc[317, '상품명'] = '블랙코미디'
kyobo.loc[323, '상품명'] = '미중전쟁'
kyobo.loc[333, '상품명'] = '해리'
kyobo.loc[334, '상품명'] = '스물아홉 생일, 1년 후 죽기로 결심했다'
kyobo.loc[354, '상품명'] = '어린 왕자'
kyobo.loc[357, '상품명'] = '살인의 문'
kyobo.loc[378, '상품명'] = '나의 문화유산답사기 : 산사 순례'
kyobo.loc[382, '상품명'] = '오리진'
kyobo.loc[390, '상품명'] = '죽음'
kyobo.loc[393, '상품명'] = '유럽 도시 기행'
kyobo.loc[396, '상품명'] = '설문석의 삼국지'
kyobo.loc[398, '상품명'] = '천년의 질문'
kyobo.loc[407, '상품명'] = '2019 제10회 젊은작가상 수상작품집'
kyobo.loc[408, '상품명'] = '직지'
kyobo.loc[431, '상품명'] = '대변동 : 위기, 선택, 변화'
kyobo.loc[436, '상품명'] = '데미안'
kyobo.loc[467, '상품명'] = '1일 1페이지, 세상에서 가장 짧은 교양 수업 365 : 인물편'
kyobo.loc[469, '상품명'] = '기억'
kyobo.loc[494, '상품명'] = '트바로티, 김호중'
kyobo.loc[500, '상품명'] = '양준일 MAYBE'
kyobo.loc[527, '상품명'] = '브람스를 좋아하세요...'
kyobo.loc[534, '상품명'] = '미라클 모닝'
kyobo.loc[548, '상품명'] = '마지막 몰입'
kyobo.loc[549, '상품명'] = '2021 제12회 젊은작가상 수상작품집'
kyobo.loc[552, '상품명'] = '햇빛은 찬란하고 인생은 귀하니까요'
kyobo.loc[562, '상품명'] = '럭키 LUCKY'
kyobo.loc[564, '상품명'] = '문명'
kyobo.loc[573, '상품명'] = '듄 신장판 1'
kyobo.loc[576, '상품명'] = '미드나잇 선'
kyobo.loc[589, '상품명'] = '서울 자가에 대기업 다니는 김 부장 이야기 1 : 김 부장 편'
kyobo.loc[596, '상품명'] = '부의 품격'
kyobo.loc[612, '상품명'] = '유럽 도시 기행'
kyobo.loc[618, '상품명'] = '벌거벗은 세계사 : 사건편'
kyobo.loc[631, '상품명'] = '컬러愛 물들다'

In [ ]:
kyobo

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면,김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽 The One Thing,게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791190382915,생에 감사해,김혜자,시/에세이,NaN,"우리들의 배우 김혜자의 연기, 인생\n“그럼에도 불구하고, 생에 감사해”\n\n한국..."
3,9791161571188,불편한 편의점,김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
4,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
...,...,...,...,...,...,...
634,9791162542569,하루를 48시간으로 사는 마법,이재은,자기계발,NaN,“무심코 허비했던 당신의 하루를 되돌려드립니다!”\n‘방송국 헤르미온느’ 이재은 아...
635,9788972773641,호감 가는 말투에는 비밀이 있다,장신웨,자기계발,NaN,오해는 줄이고 이해는 높이는 말하기를 배우다!\n중국의 최대 포털 사이트 바이두의 ...
636,9791165345204,책들의 부엌,김지혜,소설,NaN,★★★ 《책들의 부엌》 50쇄 기념 인사이드 에디션 출간 ★★★\n일상에서 벗어나고...
637,9788931011623,사랑의 기술,에리히 프롬,인문,NaN,에리히 프롬의 마지막을 함께한 라이너 풍크 박사의 \n《사랑의 기술》 50주년 기념...
638,9791192237022,고민의 답,글배우,자기계발,NaN,“고민의 답”\n“인생에 답을 모르겠을 때 답을 찾게 해준 책“ 일과 사랑 모든 고...

In [ ]:
# 없는 책 목록 골라내기
kyobo_list = book_rating[book_rating['book'].map(lambda x: x in list(kyobo['상품명']))]

In [ ]:
len(kyobo_list['book'].unique())

501

In [ ]:
kyobo_list

                 user              book  book_ID  rating
7       DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
21      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
51      DgwxAeQYNxrMj              사피엔스  b4QJB5B     5.0
60      DgwxAeQYNxrMj             인간 실격  bokNjW4     4.0
83      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
...               ...               ...      ...     ...
349661  17ovVzDWLvzyn               시크릿  bo65gG7     0.5
349667  17ovVzDWLvzyn           노르웨이의 숲  bo6bDmd     4.0
349734  17ovVzDWLvzyn             어린 왕자  bovqv5J     4.0
349741  17ovVzDWLvzyn              연금술사  byPAWG9     3.5
349754  17ovVzDWLvzyn   멈추면, 비로소 보이는 것들  byaOv5x     2.5

[34227 rows x 4 columns]

In [ ]:
kyobo_sel = kyobo[kyobo['상품명'].map(lambda x: x in list(kyobo_list['book'].unique()))]
kyobo_sel.reset_index(drop=True, inplace=True)
kyobo_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면,김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽 The One Thing,게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791161571188,불편한 편의점,김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
3,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
4,9788936438838,아버지의 해방일지,정지아,소설,NaN,"새삼스럽게 경탄스럽다!\n압도적인 몰입감, 가슴 먹먹한 감동\n정지아의 손끝에서 펼..."
...,...,...,...,...,...,...
513,9791192227481,12 1/2 부와 성공을 부르는 12가지 원칙,게리 바이너척,자기계발,NaN,“출판업계 최초 24시간 만에 100만 부 팔린 책”\n뉴욕타임스 베스트셀러 작가 ...
514,9791162542569,하루를 48시간으로 사는 마법,이재은,자기계발,NaN,“무심코 허비했던 당신의 하루를 되돌려드립니다!”\n‘방송국 헤르미온느’ 이재은 아...
515,9788972773641,호감 가는 말투에는 비밀이 있다,장신웨,자기계발,NaN,오해는 줄이고 이해는 높이는 말하기를 배우다!\n중국의 최대 포털 사이트 바이두의 ...
516,9791165345204,책들의 부엌,김지혜,소설,NaN,★★★ 《책들의 부엌》 50쇄 기념 인사이드 에디션 출간 ★★★\n일상에서 벗어나고...
517,9788931011623,사랑의 기술,에리히 프롬,인문,NaN,에리히 프롬의 마지막을 함께한 라이너 풍크 박사의 \n《사랑의 기술》 50주년 기념...

In [ ]:
# 추출된 책 평점 데이터에서 (user, book) 중복되는 데이터 선택
kyobo_list[kyobo_list.duplicated(subset=['user','book'])]['book'].unique()

array(['일의 기쁨과 슬픔', '블랙코미디', '미움받을 용기', '종의 기원', '너의 이름은.', '정의란 무엇인가',
       '멋진 신세계', '죽고 싶지만 떡볶이는 먹고 싶어', '축구를 하며 생각한 것들',
       '지적 대화를 위한 넓고 얕은 지식', '달러구트 꿈 백화점', '소설 보다 : 여름', '작은 아씨들',
       '사랑의 기술', '채식주의자', '기분이 태도가 되지 않게', '페스트', '청춘의 독서',
       '너의 췌장을 먹고 싶어', '연금술사', '고래', '북유럽 신화', '데일 카네기 인간관계론', '그림의 힘',
       '사랑의 온도', '빨강 머리 앤', '어린 왕자', '사피엔스', '인간 실격', '코스모스', '유럽 도시 기행',
       '아몬드', '회복탄력성', '고양이', '어떻게 살 것인가', '내가 죽으면 장례식에 누가 와줄까',
       '참을 수 없는 존재의 가벼움', '초역 니체의 말'], dtype=object)

In [ ]:
kyobo_list[kyobo_list['book']=='소설 보다 : 여름']

                 user        book  book_ID  rating
12785   WwRqoRDNyxlzB  소설 보다 : 여름  byXrANE     4.0
16994   YaR5YKErEqgX1  소설 보다 : 여름  b98NnW3     3.5
16997   YaR5YKErEqgX1  소설 보다 : 여름  b98NnW3     3.0
17320   g64qz8odM5ER0  소설 보다 : 여름  byXrANE     4.0
29502   nkPvrbOeNvgar  소설 보다 : 여름  byXrANE     2.5
33556   j4PxO7Anoxp0Q  소설 보다 : 여름  byXrANE     3.5
112077  8nPvyVZWo5Yo0  소설 보다 : 여름  b98NnW3     3.5
112119  8nPvyVZWo5Yo0  소설 보다 : 여름  b98NnW3     4.0
115674  4WLxZLj2rvroA  소설 보다 : 여름  b98NnW3     4.0
115712  4WLxZLj2rvroA  소설 보다 : 여름  b98NnW3     4.5
142622  yKZx3kjVOx4dJ  소설 보다 : 여름  byXrANE     4.5
144063  17ovVeEPPqzyn  소설 보다 : 여름  b98NnW3     3.5
144065  17ovVeEPPqzyn  소설 보다 : 여름  b98NnW3     4.0
144066  17ovVeEPPqzyn  소설 보다 : 여름  b98NnW3     3.0
144986  YMKqm1B9RqloD  소설 보다 : 여름  b98NnW3     4.0
147027  JZ4vBgakG5RXO  소설 보다 : 여름  byXrANE     3.5
156519  WRQxDVYPrvdl9  소설 보다 : 여름  byXrANE     3.5
179601  Pznx93Wjzv761  소설 보다 : 여름  byXrANE     3.5
197103  3Bnvw2J0pqPAY  소설 보다 : 여름  byXrANE     3.5
197422  ZBm5R40ODqd46  소설 보다 : 여름  b98NnW3     2.5
199006  jae5W4GPGx1P3  소설 보다 : 여름  byXrANE     3.5
209214  nkPvrOX1E5gar  소설 보다 : 여름  byXrANE     3.0
218862  ZBm5RJgWy5d46  소설 보다 : 여름  b98NnW3     3.5
218884  ZBm5RJgWy5d46  소설 보다 : 여름  b98NnW3     3.5
236228  QJgAx8AaMqLbO  소설 보다 : 여름  byXrANE     4.5
256399  Mr95nWMllxZPG  소설 보다 : 여름  byXrANE     5.0
260214  87Gv7O3WlvE6o  소설 보다 : 여름  b98NwNQ     1.0
266931  yKZx33p8ox4dJ  소설 보다 : 여름  byXrANE     3.0
279464  ld0q0j2PO56Xn  소설 보다 : 여름  b98NnW3     4.0
281264  6ewxa6RpWqQ1m  소설 보다 : 여름  byXrANE     3.0
299877  R6OvK7DEYvN8V  소설 보다 : 여름  byXrANE     4.0
338582  WwRqoK2NXqlzB  소설 보다 : 여름  b98NwNQ     4.5
341163  87Gv77KyLvE6o  소설 보다 : 여름  b98NnW3     4.0
349305  7gdxdWzay5GYJ  소설 보다 : 여름  byXrANE     3.0

In [ ]:
kyobo_list[kyobo_list['book']=='소설 보다 : 여름']['book_ID'].unique()

array(['byXrANE', 'b98NnW3', 'b98NwNQ'], dtype=object)

In [ ]:
# 이름만 같은 완전 다른 책 목록
book_list1 = ['일의 기쁨과 슬픔', '종의 기원', '멋진 신세계', '정의란 무엇인가', '사랑의 기술', '연금술사', '고래', '북유럽 신화',
              '사랑의 온도', '어린 왕자', '코스모스', '고양이', '어떻게 살 것인가']

In [ ]:
# 버릴 책 목록
rem_list = ['boNv5R1','b9rjA0m','b9RlL06','byK567D','b4DqrEo','byK5rvj','b9r1bDy','b4QJwmB','b401XqO','byzGdRW','b4Q5Ykl','bopbZGP',
            'bymdWJB','b9JMPeL', 'bydqD39','b4Q50qD', 'b9nDvMx','boNQ7L3', 'bovM7vJ']

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='소설 보다 : 여름']

,상품코드,상품명,인물,분야,분류기호,책 소개
163,9788932041575,소설 보다 : 여름,공현진 외,소설,NaN,새로운 세대가 그려내는 여름의 소설적 풍경\n\n독자에게 늘 기대 이상의 가치를 전...

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='초역 니체의 말']['책 소개'].values

array(['세상에 알려지지 않은 니체가 여기에 있다\n일본 아마존 인문 분야 1위, \n해당 분야 역대 최다 판매 부수를 기록한 베스트셀러\n\n무언가 뚜렷하게 잘못된 것은 없지만 그렇다고 홀가분히 하루를 마치며 편안하게 잠자리에 들 수 없을 때가 있다. 딱히 어떤 말로 표현하기는 힘든, 막막하고 고독한 이 마음을 누군가에게는 이해받고 또 위로받고 싶은 순간이 있다. 《초역 니체의 말》은 그러한 당신에게 담담한 위로와 희망의 말을 건넨다.\n《초역 니체의 말》은 역사상 가장 위대한 철학자 중 하나로 꼽히는 프리드리히 니체의 글 가운데, 철학과 종교에 관한 해설서의 명쾌함으로 정평이 나 있는 일본의 작가 시라토리 하루히코가 편번역을 맡아 엄선한 232편의 명언을 담은 책이다. 다소 어렵게 느껴졌던 기존 니체의 분위기에서 벗어나 대중에게 좀 더 가까이 다가갈 수 있도록 새롭게 엮어진 《초역 니체의 말》은, 시대를 뛰어넘는 날카로운 통찰력과 함께 현대를 사는 우리의 내면을 자극하는 섬세한 감성으로 찾아온다. 니체의 철학과 강인한 생기, 보다 고귀한 자아를 향해 나아가려는 굳은 의지가 참신하고 짧은 산문체의 글 토막에 고스란히 담겨 있다. 이미 일본에서는 2010년 1월 출간 시점부터 현재까지 200만이 넘는 독자들이 이 책을 통해 희망과 위로를 얻고 있으며 그 행진은 아직까지도 진행형이다.\n왜 이토록 《초역 니체의 말》에 열광을 하는 것일까? 니체의 말은 어떠한 철학자보다 강한 흡입력과 통찰력이 있는 짧은 산문체의 글 토막으로 독자에게 다가온다. ‘타인에게 잘 보이기 위한 나’, ‘사회에서 무난하게 살아가기 위한 나’를 만드는 충고가 아닌, 오로지 제대로 된 ‘나’ 자체를 발견하는 시간에 대해 이야기하는 책이다. 다른 무엇보다 온전한 ‘나’를 위한 삶을 먼저 찾아볼 것을 말한다. 그 목소리에는 많은 이들이 쉽게 공감할 수 있되, 특유의 날카로움은 잃지 않은 담담한 어조로 읊조리는 현실의 감성이 묻어난다. 이러한 니체의 말은 복잡한 현대를 살아가는 우리들에게 잠시나마 자신을 되돌아보는 여유와 온기 어린 위로를 가져다준다.\n니체 특유의 날카롭고 직설적인 화법을 통해 마음을 사로잡는 강력한 매력이 묻어나는 《초역 니체의 말》은 232편의 짧은 글이 10개의 주제로 나뉘어 수록되어 있다. 나 자신에 대한 것으로 시작해 기쁨, 삶, 마음, 친구, 세상, 인간, 사랑, 지성, 아름다움에 대한 명문장들을 읽다 보면 무릎을 탁 치며 찾아오는 깨달음에 전율을 느낄 것이다. 니체의 문장 자체가 흥분시키기보다는 읽는 사람 스스로 자극과 영감을 받는다는 것에 흥분을 느끼는 것이다. 추운 겨울을 코앞에 둔 지금, 19세기 철학자의 뛰어난 통찰력과 날카로움, 삶에 대한 긍정이 담긴 《초역 니체의 말》로 마음을 데워 보는 건 어떨까.'],
      dtype=object)

In [ ]:
# 소설 보다 : 여름 => 삭제
kyobo_list.drop(kyobo_list[kyobo_list['book']=='소설 보다 : 여름'].index, inplace=True)

In [ ]:
# 책 목록 중복 확인
kyobo_sel[kyobo_sel.duplicated('상품명')]

,상품코드,상품명,인물,분야,분류기호,책 소개
65,9791165343729,달러구트 꿈 백화점,이미예,소설,NaN,"100만 독자를 사로잡은 《달러구트 꿈 백화점》, 그 두 번째 이야기\n\n어느덧 ..."
86,9791192412351,데일 카네기 자기관리론,데일 카네기,자기계발,NaN,걱정 없이 살게 해줄 가장 효과적인 실행법!\n\n데일 카네기는 이 책의 집필을 위...
102,9791190313193,지적 대화를 위한 넓고 얕은 지식,채사장,인문,NaN,"수백만 독자가 읽고 열광하고, 수년간 인문학 필수 도서로 자리 잡은\n대표 인문학 ..."
151,9788934972464,사피엔스,유발 하라리,인문,NaN,출간 10주년·200쇄·115만부 기념\n유발 하라리 특별 서문 수록\n“인공지능의...
170,9791187119845,나는 나로 살기로 했다,김수현,시/에세이,NaN,진짜 ‘나’로 살기 위한 뜨거운 조언들! 어른이 처음인 당신을 위한 단단한 위로들!...
199,9788936434267,아몬드,손원평,소설,NaN,"&lt;완득이&gt;, &lt;위저드 베이커리&gt;를 잇는 제10회 창비청소년문학..."
212,9788996991342,미움받을 용기,기시미 이치로 외,인문,NaN,2014 아마존 일본 ‘종합’ 베스트셀러 1위. &lt;미움받을 용기&gt;는 아들...
242,9788972773207,하버드 첫 강의 시간관리 수업,쉬셴장,자기계발,NaN,하버드의 가장 큰 경쟁력은 1분이다\n\n애플의 CEO 팀쿡은 새벽 4시면 일어나서...
257,9791186560655,미움받을 용기,기시미 이치로 외,인문,NaN,"이미 이 시대의 고전이 된 책!\n2015년, 2016년, 2017년 압도적 인기의..."
271,9791159031076,데미안,헤르만 헤세,소설,NaN,헤르만 헤세가 1919년 ‘에밀 싱클레어’라는 가명으로 출판한 소설『데미안』을 오리...
331,9791159036514,데미안,헤르만 헤세,소설,NaN,"헤르만 헤세 탄생 140주년 기념 초호화 패브릭 양장\n영혼의 성장 기록, 나를 찾..."
380,9791130630762,아비투스,도리스 메르틴,인문,NaN,독일 최고의 컨설턴트 도리스 메르틴의 부와 성공에 대한 통념을 뒤집는 탁월한 통찰\...
383,9788901243658,기분이 태도가 되지 않게,레몬심리,자기계발,NaN,"집에서, 회사에서, 인간관계에서 \n후회가 사라지고 오해가 줄어드는 기분 사용법\..."
417,9791164452125,페스트,알베르 카뮈,소설,NaN,노벨 문학상 수상 작가 알베르 카뮈의 대표작\n사회 부조리에 대한 묘사와 인간 심리...
482,9791158741051,심리학을 만나 행복해졌다,장원청,자기계발,NaN,150만 중국 독자의 삶을 바꾸고\n국내 10만 독자가 극찬한 심리학 베스트셀러\n...
489,9791191891072,나에게 고맙다,전승환,시/에세이,NaN,200만 독자가 사랑하는 ‘책 읽어주는 남자’ 전승환의 마음 처방전\n“내가 가장 ...
496,9788965137702,유럽 도시 기행,유시민,인문,NaN,"유시민의 3년 만에 돌아온 신작,\n《유럽도시기행 2》는 시대의 격랑을 이겨내고 저..."

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='나에게 고맙다']

,상품코드,상품명,인물,분야,분류기호,책 소개
267,9788968330889,나에게 고맙다,전승환,시/에세이,NaN,페이스북ㆍ인스타그램ㆍ카카오스토리\n100만 독자의 마음을 10년 동안 어루만진 〈책...
489,9791191891072,나에게 고맙다,전승환,시/에세이,NaN,200만 독자가 사랑하는 ‘책 읽어주는 남자’ 전승환의 마음 처방전\n“내가 가장 ...

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='나에게 고맙다']['책 소개'].values

array(['페이스북ㆍ인스타그램ㆍ카카오스토리\n100만 독자의 마음을 10년 동안 어루만진 〈책 읽어주는 남자〉\n오늘, 당신의 마음을 읽고 다독이다\n\n10여 년 동안 한결같이 좋은 글귀로 위안을 주던 ‘책 읽어주는 남자’가 이번에는 책이 아닌 당신의 마음을 사려 깊게 읽고 다독인다. 〈책 읽어주는 남자〉의 토닥토닥 에세이 《나에게 고맙다》는 어쩌면 세상 가장 흔한 말이지만, 정작 내게는 한 번도 건네지 못했던 말들이 담겨 있다. 거창한 말도, 특별한 고백도 아니다. 그저 “고마워”, “괜찮아”, “오늘도 수고했어”처럼 내 주위 사람들에게는 숱하게 해 주었던 위로와 감사의 표현이다. 남들 신경 쓰느라, 주변 눈치 보느라 유독 인색하기만 했던 나에게 적어도 오늘만큼은 진심 어린 위로와 감사의 인사를 건네 보자.',
       '200만 독자가 사랑하는 ‘책 읽어주는 남자’ 전승환의 마음 처방전\n“내가 가장 고마워해야 할 사람은\n바로 나예요.”\n\n7년 만에 새롭게 선보이는 에세이스트 전승환의 데뷔작\n《나에게 고맙다》 30만 부 판매 기념 전면 개정판 출간\n\n2016년 출간 이후 30만 부 넘게 판매된 명실상부 대한민국 대표 힐링 에세이 《나에게 고맙다》가 7년 만에 새롭게 단장하여 출간된다. 200만 독자가 사랑하는 책큐레이션 플랫폼 ‘책 읽어주는 남자’ 편집장 전승환 작가의 데뷔작인 《나에게 고맙다》는 출간 즉시 그해 교보문고, 예스24, 인터파크에서 ‘올해의 책’으로 꼽히기도 했으며, 출간 후 7년 간 에세이 베스트 자리를 지켜온 스테디셀러이다. 전 세대에게 폭넓은 인기를 끌며 일본과 태국 등에 수출되었고, 박효신, 송민호, 소유진, 노홍철, 에이핑크 보미, 권율, 서지혜, 신지 등 스타가 먼저 찾아 읽고 추천한 에세이로 유명세를 떨치기도 했다.\n2022년, 7년 만의 전면 개정판으로 선보이는 《나에게 고맙다》에서는 기존 책에 실렸던 사진을 과감히 삭제하고, 아름다운 순간을 포착하는 사진가 빛담(@put_in_light)과의 콜라보레이션을 통해 책의 분위기를 완전히 바꾸어 놓았다. 오래된 글의 일부는 과감히 덜어내고, 요즈음을 살아가는 독자들에게 전하고 싶은 따뜻한 마음을 담은 40여 편의 글을 새로 써 책에 담아냈다.\n지금까지 한 번도 스스로에게 ‘고맙다’는 말을 전해보지 못했다면, 그동안 고생한 나에게 한 마디 소중한 위로를 건네고 싶다면, 전승환 작가가 세심하게 공들여 매만진 《나에게 고맙다》 전면 개정판을 만나보자. 북테라피스트 전승환의 따스한 문장들이 그 어떤 위로보다 깊이 마음을 어루만져줄 것이다.'],
      dtype=object)

In [ ]:
# 시리즈물 하나만 남기기
kyobo_sel.drop([57,257], inplace=True) # 미움받을 용기
kyobo_sel.drop([102], inplace=True) # 지적대화를 위한 ~
kyobo_sel.drop([163], inplace=True) # 소설보다 : 여름
kyobo_sel.drop([123], inplace=True) # 기분이 태도가 되지 않게
kyobo_sel.drop([65], inplace=True) # 달러구트 꿈 백화점
kyobo_sel.drop([417], inplace=True) # 페스트
kyobo_sel.drop([27], inplace=True) # 사피엔스
kyobo_sel.drop([496], inplace=True) # 유럽 도시 기행
kyobo_sel.drop([68], inplace=True) # 아몬드
kyobo_sel.drop([17], inplace=True) # 데일 카네기 자기 관리론
kyobo_sel.drop([74], inplace=True) # 나는 나로 살기로 했다
kyobo_sel.drop([92], inplace=True) # 하버드 시간 관리
kyobo_sel.drop([46,271], inplace=True) # 데미안
kyobo_sel.drop([143], inplace=True) # 아비투스
kyobo_sel.drop([482], inplace=True) # 심리학을 만나 행복해졌다
kyobo_sel.drop([489], inplace=True) # 나에게 고맙다

In [ ]:
kyobo_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면,김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽 The One Thing,게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791161571188,불편한 편의점,김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
3,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
4,9788936438838,아버지의 해방일지,정지아,소설,NaN,"새삼스럽게 경탄스럽다!\n압도적인 몰입감, 가슴 먹먹한 감동\n정지아의 손끝에서 펼..."
...,...,...,...,...,...,...
513,9791192227481,12 1/2 부와 성공을 부르는 12가지 원칙,게리 바이너척,자기계발,NaN,“출판업계 최초 24시간 만에 100만 부 팔린 책”\n뉴욕타임스 베스트셀러 작가 ...
514,9791162542569,하루를 48시간으로 사는 마법,이재은,자기계발,NaN,“무심코 허비했던 당신의 하루를 되돌려드립니다!”\n‘방송국 헤르미온느’ 이재은 아...
515,9788972773641,호감 가는 말투에는 비밀이 있다,장신웨,자기계발,NaN,오해는 줄이고 이해는 높이는 말하기를 배우다!\n중국의 최대 포털 사이트 바이두의 ...
516,9791165345204,책들의 부엌,김지혜,소설,NaN,★★★ 《책들의 부엌》 50쇄 기념 인사이드 에디션 출간 ★★★\n일상에서 벗어나고...
517,9788931011623,사랑의 기술,에리히 프롬,인문,NaN,에리히 프롬의 마지막을 함께한 라이너 풍크 박사의 \n《사랑의 기술》 50주년 기념...

In [ ]:
kyobo_list.reset_index(drop=True, inplace=True)
kyobo_list

                user              book  book_ID  rating
0      DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
1      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
2      DgwxAeQYNxrMj              사피엔스  b4QJB5B     5.0
3      DgwxAeQYNxrMj             인간 실격  bokNjW4     4.0
4      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
...              ...               ...      ...     ...
34188  17ovVzDWLvzyn               시크릿  bo65gG7     0.5
34189  17ovVzDWLvzyn           노르웨이의 숲  bo6bDmd     4.0
34190  17ovVzDWLvzyn             어린 왕자  bovqv5J     4.0
34191  17ovVzDWLvzyn              연금술사  byPAWG9     3.5
34192  17ovVzDWLvzyn   멈추면, 비로소 보이는 것들  byaOv5x     2.5

[34193 rows x 4 columns]

In [ ]:
len(kyobo_list['book'].unique())

500

In [ ]:
# 이름만 같은 완전 다른 책 평점 처리
rating_book1 = pd.DataFrame()

for title in book_list1:
    df = kyobo_list[kyobo_list['book']==title]
    user = list(df[df.duplicated(subset='user')]['user'].values)
    user_df1 = df[df['user'].map(lambda x: x in user)]
    user_df2 = df[df['user'].map(lambda x: x not in user)]
    user_df1 = user_df1.drop_duplicates()
    user_df2 = user_df2[user_df2['book_ID'].map(lambda x: x not in rem_list)]
    new_df = pd.concat([user_df1, user_df2])
    rating_book1 = pd.concat([rating_book1, new_df])

In [ ]:
# drop 안된 나머지 중복 책들에 대해 수작업
rating_book1[rating_book1.duplicated(['user','book'])][60:]

                user       book  book_ID  rating
24658  3Bnvw0nE6p5PA       연금술사  b4DNYQG     5.0
3523   nkPvr19OWqgar         고래  b4QJwmB     3.0
12992  Pznx9Pl2a5761         고래  b40YEEo     5.0
13613  Mr95nAagjvZPG         고래  b4QJwmB     4.5
18105  86ADvGReWqzZl         고래  b40YEEo     3.0
20536  ZBm5RJgWy5d46         고래  b40YEEo     3.0
26258  VRZv4XY1Bvr6y         고래  b40YEEo     4.0
28724  JgAx8ddMwxLbO         고래  b40YEEo     3.5
3997   VRZv4ePYE15r6     북유럽 신화  b4MbkLj     4.0
4065   VRZv4ePYE15r6     사랑의 온도  byzGdRW     3.5
4085   VRZv4ePYE15r6      어린 왕자  bopbZGP     5.0
5106   nkPvrbKkWvgar       코스모스  b9JMPeL     4.5
10456  17ovVVL3rvzyn       코스모스  b42ANzd     3.0
25688  YaR5YNkzlxgX1       코스모스  bydqD39     5.0
28153  Jgkql1MLnvX0b       코스모스  b9JMPeL     5.0
20193  2mwvgKpm4vMa7  어떻게 살 것인가  boNQ7L3     4.5

In [ ]:
rating_book1[rating_book1['user']=='2mwvgKpm4vMa7']

                user       book  book_ID  rating
20174  2mwvgKpm4vMa7  일의 기쁨과 슬픔  b9nDdXx     5.0
20177  2mwvgKpm4vMa7  어떻게 살 것인가  boNQ7L3     2.0
20193  2mwvgKpm4vMa7  어떻게 살 것인가  boNQ7L3     4.5

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='어떻게 살 것인가']

,상품코드,상품명,인물,분야,분류기호,책 소개
179,9788965132288,어떻게 살 것인가,유시민,인문,NaN,"자유인으로 돌아온 유시민, '어떻게 살 것인지'에 대해 되짚어본다!\n\n정치인에서..."

In [ ]:
drop_idx = [12944,24966,4075,4022,4854,5344,5567,5993,12768,15085,17579,19006,19897,20535,25761,30545,30987,94,2352,6380,6777,
            9785,10768,12598,17665,23126,29405,91,543,2347,2684,6114,6893,8344,11258,13267,14243,16579,18114,22065,22523,23877,
            31311,1771,2778,11253,12623,18350,18437,24085,27401,28887,29016,33575,33945,33994,6102,8142,11007,11918,24658,3512,
            12992,13609,18105,20536,26258,28724,3997,4055,4065,3994,5088,10456,25675,28062,20177]

In [ ]:
rating_book1.drop(drop_idx, inplace=True)
rating_book1

                user       book  book_ID  rating
18     3BnvwpKaj5PAY  일의 기쁨과 슬픔  b9nDdXx     3.0
5048   dP8v638205WeJ  일의 기쁨과 슬픔  b9nDdXx     4.0
12223  nb4xk2zbd5OAz  일의 기쁨과 슬픔  b9nDdXx     4.0
12943  Q9L5pdleY5Nb0  일의 기쁨과 슬픔  b9nDdXx     4.0
24951  VRZv4n71Bxr6y  일의 기쁨과 슬픔  b9nDdXx     4.5
...              ...        ...      ...     ...
33727  jae5WAOEXq1P3  어떻게 살 것인가  byPY2YR     2.5
34010  DgwxAMgQgxrMj  어떻게 살 것인가  byPY2YR     4.0
34092  2mwvgN8e2qMa7  어떻게 살 것인가  byPY2YR     2.5
34123  WRQxDQ011qdl9  어떻게 살 것인가  byPY2YR     0.5
34137  7gdxdWzay5GYJ  어떻게 살 것인가  byPY2YR     3.0

[4400 rows x 4 columns]

In [ ]:
# 시리즈물/에디션/특별판 책 평점 처리
dup_book = list(kyobo_list[kyobo_list.duplicated(subset=['user','book'])]['book'].unique())
book_list2 = [book for book in dup_book if book not in book_list1]
rating_book2 = pd.DataFrame()

for title in book_list2:
    df = kyobo_list[kyobo_list['book']==title]
    user = list(df[df.duplicated(subset='user')]['user'].values)
    user_df1 = df[df['user'].map(lambda x: x in user)]
    user_df2 = df[df['user'].map(lambda x: x not in user)]
    rating_avg = user_df1.groupby('user').mean()
    rating_avg = rating_avg.rename(columns={'rating':'rating_avg'})
    rating_avg.reset_index(inplace=True)
    new_df1 = pd.merge(user_df1, rating_avg)
    new_df1.drop(['rating'], axis=1, inplace=True)
    new_df1 = new_df1.rename(columns={'rating_avg':'rating'})
    new_df1.drop_duplicates(subset='user', inplace=True)
    new_df = pd.concat([new_df1, user_df2])
    rating_book2 = pd.concat([rating_book2, new_df])

In [ ]:
rating_book2

                user      book  book_ID  rating
0      3BnvwpKaj5PAY     블랙코미디  b407XlY    1.75
158    ZBm5Ry4Wyvd46     블랙코미디  byEaNwQ    4.00
678    YaR5YG9D4qgX1     블랙코미디  byEaNwQ    3.50
819    VRZv4n39Pxr6y     블랙코미디  byEaNwQ    3.00
1222   8BRveaOXJv6VJ     블랙코미디  byEaNwQ    3.00
...              ...       ...      ...     ...
27825  ZWpqM79XL5rkn  초역 니체의 말  byKxqj9    3.50
29448  VRZv4oEBZqr6y  초역 니체의 말  byKxqj9    3.50
30350  4WLxZd2K8vroA  초역 니체의 말  byKxqj9    4.00
30790  4WLxZAnOm5roA  초역 니체의 말  byKxqj9    5.00
30959  WwRqodNY2vlzB  초역 니체의 말  byKxqj9    3.50

[4473 rows x 4 columns]

In [ ]:
no_dup = kyobo_list[kyobo_list['book'].map(lambda x: x not in dup_book)]
no_dup

                user              book  book_ID  rating
0      DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
1      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
4      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
6      DgwxAeQYNxrMj       소크라테스 익스프레스  bo5qAzM     3.5
8      DgwxAeQYNxrMj        미드나잇 라이브러리  byzQq6k     2.0
...              ...               ...      ...     ...
34186  17ovVzDWLvzyn           오직 두 사람  byXA8a9     4.0
34187  17ovVzDWLvzyn        약간의 거리를 둔다  bo57xYj     2.5
34188  17ovVzDWLvzyn               시크릿  bo65gG7     0.5
34189  17ovVzDWLvzyn           노르웨이의 숲  bo6bDmd     4.0
34192  17ovVzDWLvzyn   멈추면, 비로소 보이는 것들  byaOv5x     2.5

[24756 rows x 4 columns]

In [ ]:
new_book_rating = pd.concat([no_dup, rating_book1, rating_book2]);
new_book_rating.reset_index(drop=True, inplace=True)
new_book_rating

                user              book  book_ID  rating
0      DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
1      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
2      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
3      DgwxAeQYNxrMj       소크라테스 익스프레스  bo5qAzM     3.5
4      DgwxAeQYNxrMj        미드나잇 라이브러리  byzQq6k     2.0
...              ...               ...      ...     ...
33624  ZWpqM79XL5rkn          초역 니체의 말  byKxqj9     3.5
33625  VRZv4oEBZqr6y          초역 니체의 말  byKxqj9     3.5
33626  4WLxZd2K8vroA          초역 니체의 말  byKxqj9     4.0
33627  4WLxZAnOm5roA          초역 니체의 말  byKxqj9     5.0
33628  WwRqodNY2vlzB          초역 니체의 말  byKxqj9     3.5

[33629 rows x 4 columns]

In [ ]:
new_book_rating.pivot('user','book','rating')

book,100세 철학자의 행복론,10배의 법칙,11문자 살인사건,12 1/2 부와 성공을 부르는 12가지 원칙,1984,1cm 다이빙,"1일 1페이지, 세상에서 가장 짧은 교양 수업 365 : 인물편",2019 제10회 젊은작가상 수상작품집,2021 제12회 젊은작가상 수상작품집,2022 제13회 젊은작가상 수상작품집,...,혼자가 혼자에게,홀로서기 심리학,홈 스위트 홈,환상서점,회복탄력성,횡설수설하지 않고 정확하게 설명하는 법,효기심의 권력으로 읽는 세계사 : 유럽 편,휴먼카인드,희망의 끈,흰
user,,,,,,,,,,,,,,,,,,,,,
06nkPvrlxgarB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0LzNM5Nox26j7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV0Qrlxzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV1aGrqzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
17ovV1kA2qzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zNM5Nynjnv26j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzQDn526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzbLo526j,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzddl526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzlkd526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 서울 100선, 베스트셀러 데이터 처리

In [ ]:
seoul

,상품코드,상품명,인물,분야,분류기호,책 소개
640,9788972756194,나미야 잡화점의 기적 (히가시노 게이고 장편소설),히가시노 게이고,NaN,8.0,히가시노 게이고의 차기 대표작으로 손꼽힐 『나미야 잡화점의 기적』\n\n추리적인 향...
641,9788954655972,여행의 이유 (김영하 산문),김영하,NaN,8.0,"여행이 내 인생이었고, 인생이 곧 여행이었다!\n\n여행의 감각을 일깨우는 소설가 ..."
642,9788970129815,파친코 1 (이민진 장편소설),이민진,NaN,8.0,어디에도 속하지 못했던 자이니치들의 분노와 슬픔에서 탄생한 대작!\n\n한국계 1....
643,9788936434120,소년이 온다 (한강 장편소설),한강,NaN,8.0,고통스럽게 되살려낸 5월 광주\n\n한국인 최초 맨부커상 수상작가 한강의 여섯 번째...
644,9788954646079,바깥은 여름 (김애란 소설),김애란,NaN,8.0,우리를 실망시키지 않는 작가 김애란이 선보이는 일곱 편의 마스터피스!\n\n김애란이...
...,...,...,...,...,...,...
2607,9791189336462,헌책방 기담 수집가 (사연 있는 책을 찾아드립니다. 수수료는 당신 삶의 이야기!),윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
2608,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
2609,9791159257117,클락워크 도깨비 (경성 무한 역동 도깨비불),황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...
2610,9791136748195,비밀 THE TOP SECRET season0 (10),Reiko Shimizu,NaN,8.0,"준이치로부터 마이를 구해낸 히카루, 그리고 히카루를 진심으로 믿고 싶은 아오키."
2611,9788986022476,한그루 열두 가지,박정미,NaN,8.0,도시생활자의 마음밭에 심어보는\n일 년 열두 가지 작물\n\n공방 ‘달실’ 김기란 ...

In [ ]:
# seoul 책 중에서 kyobo_sel에 있는 책 삭제
df_cat = pd.concat([kyobo_sel, seoul])
df_cat.drop_duplicates(subset='상품코드', inplace=True)
seoul = df_cat[df_cat['분야'].isna()]
seoul

,상품코드,상품명,인물,분야,분류기호,책 소개
642,9788970129815,파친코 1 (이민진 장편소설),이민진,NaN,8.0,어디에도 속하지 못했던 자이니치들의 분노와 슬픔에서 탄생한 대작!\n\n한국계 1....
651,9788949162126,달콩이네 떡집 (만복이네 떡집 5),김리리,NaN,8.0,80만 부 돌파!\n초등 3학년 국어 교과서 수록 \n「만복이네 떡집」 시리즈 최신...
655,9788954681155,홍학의 자리 (정해연 장편소설),정해연,NaN,8.0,“이 행복이 영원할 거라고 생각한 적은 없었다.\n그러나 이런 끝을 상상한 적도 없...
656,9788997962129,망원동 브라더스 (김호연 장편소설 | 제9회 세게문학상 우수상),김호연,NaN,8.0,"상처받은 이들이여, 연체된 인생들이 모여 사는 8평 옥탑방으로 오라!\n\n김호연의..."
658,9788925588735,프로젝트 헤일메리,앤디 위어,NaN,8.0,“이름도 기억 못하는 내가 인류의 희망이라니?”\n멸망 위기의 지구 구하기 프로젝트...
...,...,...,...,...,...,...
2607,9791189336462,헌책방 기담 수집가 (사연 있는 책을 찾아드립니다. 수수료는 당신 삶의 이야기!),윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
2608,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
2609,9791159257117,클락워크 도깨비 (경성 무한 역동 도깨비불),황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...
2610,9791136748195,비밀 THE TOP SECRET season0 (10),Reiko Shimizu,NaN,8.0,"준이치로부터 마이를 구해낸 히카루, 그리고 히카루를 진심으로 믿고 싶은 아오키."
2611,9788986022476,한그루 열두 가지,박정미,NaN,8.0,도시생활자의 마음밭에 심어보는\n일 년 열두 가지 작물\n\n공방 ‘달실’ 김기란 ...

In [ ]:
# 책 이름 통일하기 (에디션, 특별판 같은 괄호 문장 제거)
seoul_idx = seoul[seoul['상품명'].map(lambda x: '(' in x)].index
seoul_modi = list(seoul.loc[seoul_idx]['상품명'])
seoul_modi = [book[:book.rindex('(')] for book in seoul_modi]
seoul_modi = [book[:book.rindex('(')] if '(' in book else book for book in seoul_modi]
seoul.loc[seoul_idx, '상품명'] = seoul_modi

In [ ]:
# 책 이름 오른쪽 공백 제거
seoul['상품명'] = seoul['상품명'].map(lambda x: x.rstrip())

In [ ]:
# 책 평점 목록
book_rating['book']

0           해리 포터와 마법사의 돌
1                    파리대왕
2                 지금 이 순간
3                      식객
4                   아웃라이어
               ...
349752            로빈슨 크루소
349753             이기는 습관
349754    멈추면, 비로소 보이는 것들
349755            우체부 프레드
349756        나의 라임 오렌지나무
Name: book, Length: 349757, dtype: object

In [ ]:
# 책 평점 목록에 존재하지 않는 책 선택
s_list = seoul[seoul['상품명'].map(lambda x: x not in list(book_rating['book']))]

In [ ]:
s_list.to_excel('서울,베스트셀러 수정 목록.xlsx')

In [ ]:
s_list[1000:1050]

,상품코드,상품명,인물,분야,분류기호,책 소개
2370,9791133447763,심야식당 18,아베 야로,NaN,8.0,ABE Yaro의 만화 『심야식당』 제18권. 이 책은 밤 12시에 문을 여는 기묘...
2371,9791161450148,나와 호랑이님 17,카넬,NaN,8.0,"『나와 호랑이님』 제17권 한정판. 이곳은 242,145번 평행세계. 세희가 변한 ..."
2372,9791133448135,식극의 소마 20,츠쿠다 유토,NaN,8.0,현 토오츠키 학교의 정점에 서있는 요리사 츠카사 에이시와의 1대1 대결! 그의 세련...
2373,9788927047858,심하게 굴지 말아줘 6,네코타 요네조우,NaN,8.0,Yonezou Nekota의 BL만화 『심하게 굴지 말아줘』 제6권. 마야에게 빌린...
2374,9788954645775,수인 1: 경계를 넘다,황석영,NaN,8.0,거장 황석영이 몸으로 써내려간 자전적 기록.\n\n작가 황석영이 몸으로 써내려간 『...
2375,9788965483717,미카엘라 1: 달빛 드레스 도난 사건,박에스더,NaN,8.0,정의 수호 소녀 미카엘라의 특별한 보물찾기!\n\n『미카엘라: 달빛 드레스 도난 사...
2376,9788954645782,수인 2: 불꽃 속으로,황석영,NaN,8.0,거장 황석영이 몸으로 써내려간 자전적 기록.\n\n작가 황석영이 몸으로 써내려간 『...
2377,9791127841669,시원찮은 그녀를 위한 육성방법 11,마루토 후미아키,NaN,8.0,"『시원찮은 그녀를 위한 육성방법』 제11권. 에리리, 우타하 선배를 모델로 한 캐릭..."
2379,9791125594970,결혼 연애,진소라,NaN,8.0,"《연애 레시피》, 《연애 연습》 에 이은 진소라의 세 번째 연애 이야기 『결혼 연애..."
2382,9791186958162,포션메이커,이금영,NaN,8.0,"인기 모바일 게임 《포션메이커》의 노벨라이즈. 《아이언 하트》, 《메이드 인 코리아..."
2385,9791133430642,판도라 하츠 24+1,Jun Mochizuki,NaN,8.0,'판도라 하츠' 세 번째 팬북이자 최후의 팬북!\n\n『판도라 하츠』메모리얼 가이드...
2387,9791127841652,데이트 어 라이브 앙코르 6,타치바나 코우시,NaN,8.0,"『데이트 어 라이브 앙코르』 제6권. 새해 첫 참배를 마친 후, 이츠카 가에서 펼쳐..."
2388,9791127841621,변변찮은 마술강사와 추상일지 1,히츠지 타로,NaN,8.0,히츠지 타로의 『변변찮은 마술강사와 추상일지』. 알자노 제국 마술학원에는 학생들도 ...
2390,9788962478396,건방진 장루이와 68일,황선미^이보연,NaN,8.0,장루이! 모든 게 그 녀석 때문이야!\n\n《마당을 나온 암탉》 《나쁜 어린이 표》...
2392,9791127841607,데스마치에서 시작되는 이세계 광상곡 8,아이나나 히로,NaN,8.0,유유자적 이세계 관광기 『데스마치에서 시작되는 이세계 광상곡』 제8권. 일하다가 잠...
2393,9791131960172,반월당의 기묘한 이야기 7,정연,NaN,8.0,『반월당의 기묘한 이야기』 제7권 특별판. 삐딱하지만 올곧은 마음을 지닌 고등학생 ...
2394,9791127841706,살육의 천사 3,사나다 마코토,NaN,8.0,나즈카 쿠단의 『살육의 천사』 제3권. 레이와 잭은 광기의 여간수 캐시가 관리하는 ...
2395,9788959135264,이동진 독서법,이동진,NaN,8.0,국민독서멘토 이동진이 알려주는 책을 사랑하는 방법\n\n‘닥치는 대로 끌리는 대로 ...
2396,9788965746201,보복대행전문주식회사 1,이외수,NaN,8.0,인간 존재의 진정한 구원이란 무엇인가!\n\n올해로 문학인생 43년을 맞은 이외수 ...
2398,9788965746218,보복대행전문주식회사 2,이외수,NaN,8.0,인간 존재의 진정한 구원이란 무엇인가!\n\n올해로 문학인생 43년을 맞은 이외수 ...
2400,9788960520158,책벌레의 하극상 제2부 신전의 견습무녀 2,카즈키 미야,NaN,8.0,『책벌레의 하극상』 제2부 《신전의 견습무녀》 제2권. 청색 견습무녀로 바쁜 나날을...
2401,9791131265413,묵향 34: 부활의 장,전동조,NaN,8.0,전동조 장편 판타지 소설 『묵향. 34: 부활의 장』. 무공의 끝을 보고자 했던 인...
2402,9788949195872,스무고개 탐정 8: 푸른 수염,허교범,NaN,8.0,아이들의 마음을 사로잡을 본격적인 심리 게임이 시작된다!\n\n제1회 스토리킹 수상...
2404,9788960532410,토지 1,박경리,NaN,8.0,박경리는 『토지』의 작가로 불린다. 『토지』는 한국문학사의 기념비적인 작품이다. 『...
2405,9791188380015,좀비고등학교 코믹스 1,배아이,NaN,8.0,"800만 다운로드를 돌파한 청소년이 가장 사랑하는 게임, 좀비고등학교가 코믹스로 탄..."
2406,9791127841683,"거미입니다만, 문제라도? 4",바바 오키나,NaN,8.0,"『거미입니다만, 문제라도?』 제4권. 꿈에도 그리던 지상. 산에서는 나무 열매를, ..."
2407,9791127841195,최약무패의 신장기룡 10,아카츠키 센리,NaN,8.0,왕도와 패도가 교차하는 학원 판타지 배틀 『최약무패의 신장기룡』 제10권. 세계 연...
2408,9791136255822,하이큐!! 45,HARUICHI FURUDATE,NaN,8.0,차세대 왕도 스포츠 만화!\n극강의 청춘 배구 스토리\n\nHaruichi Furu...
2409,9791130633572,베서니와 괴물의 묘약,잭 메기트-필립스,NaN,8.0,단숨에 읽히는 매력적인 현대의 고전!\n\n『베서니와 괴물의 묘약』에는 어린이들이 ...
2410,9791164137084,미드나잇 선 2,스테프니 메이어,NaN,8.0,로맨스의 상징 벨라와 에드워드가 돌아왔다!\n\n《트와일라잇》 시리즈의 완결『미드나...
2411,9791164137053,추리 천재 엉덩이 탐정 10,트롤,NaN,8.0,"아이큐 1,104의 천재, ‘엉덩이 탐정’과 함께 하는 추리 동화!\n\n엉덩이를 ..."
2414,9791164137176,흔한남매 별난 방탈출 1,김언정,NaN,8.0,지금부터 게임을 시작하지!\n좌충우돌 별난 방탈출의 세계로 고고!\n\n209만 유...
2420,9791164062898,이상한 과자 가게 전천당 9 9,히로시마 레이코,NaN,8.0,여행지에서 펼쳐지는 색다른 과자 이야기\n과자도 열심히 팔았으니 잠시 여행을 다녀오...
2421,9791136252982,하이큐!! 44,HARUICHI FURUDATE,NaN,8.0,괴변학파 요츠야 선배의 괴담의 후루타테 하루이치 신작!\n이것이 바로 정통 스포츠 ...
2423,9791190980302,좀비고등학교 코믹스 22,유대영,NaN,8.0,청소년이 사랑하는 게임 ‘좀비고등학교’가 코믹스로 탄생!\n\n좀비고등학교 게임 마...
2424,9788960906549,이해인의 말,이해인,NaN,8.0,"시 쓰는 수도자, 인간적 고뇌와 문학적 지향 \n시와 영성의 조화를 꿈꿔온 이해인 ..."
2433,9788954676397,극락왕생 2,고사리박사,NaN,8.0,"소설가 정세랑 강력 추천!\n\n“힘있는 서사에 먼저 끌렸고 이어, 올해 만나지 못..."
2437,9791165794002,코드네임 C,강경수,NaN,8.0,세계가 열광할 K-첩보물의 등장! 〈코드네임〉 시리즈 \n볼로냐 라가치 상 수상 작...
2439,9788934978947,내 안의 평온을 아껴주세요,정민,NaN,8.0,11만 구독자의 하루를 여는 유튜브 채널 마인드풀tv\n‘평온보스’ 정민이 전하는 ...
2441,9791136260475,길티 이노센스 4,윤한,NaN,8.0,"""살인자로 다시 만난 당신과 나.\n하지만 아무것도 변하지 않아라는 말을 난 믿고 ..."
2443,9788955825893,설날,김영진,NaN,8.0,"★ 김영진 그림책 열세 번째 이야기 ★\n맛있는 떡국도 실컷 먹고,\n윷놀이도 하고..."
2445,9791136260017,열혈강호 82,전극진,NaN,8.0,사파 최고의 인물인 천마신군의 제자 한비광과 정파 최고의 기인인 검황의 손녀딸 담화...
2446,9791186602607,시크 THICK,트레시 맥밀런 코텀,NaN,8.0,"“현재 나의 사회적 지위는 우리 사회에 대해 무엇을 말해주는가?”\n ‘인종, 젠..."
2447,9791191187564,엄마 박완서의 부엌: 정확하고 완전한 사랑의 기억,호원숙,NaN,8.0,오직 딸이라서 가능한 박완서 문학의 코멘터리\n엄마 박완서의 손길과 입김이 닿았던 ...
2450,9791166255465,코믹 문호 스트레이독스 19,아사기리 카프카(원작),NaN,8.0,천공 카지노에서 낙하한 시그마를 살려준 사람은 죽었다고 생각한 마술사 고골이었다.\...
2451,9791166113987,전생했더니 슬라임이었던 건에 대하여 17,후세,NaN,8.0,‘전생 슬라임’ 본편과는 다른 시점에서 그려지는 주옥같은 단편집!\n\n쥬라 템페스...
2452,9788954674911,극락왕생 1,고사리박사,NaN,8.0,"“먼 여행이 끝나 나는 다시 돌아왔습니다.\n언젠가 홀로 멀리 떠나간 적 있는, 깊..."
2453,9788954677189,나의 마녀 3: 유리그릇,해윤,NaN,8.0,"너를 위해서라면 무엇이든 할 수 있어\n사랑에 미친 마녀들의 이야기, 그 세번째\n..."
2454,9788925589091,고래별 3,나윤희,NaN,8.0,"“내가 정말 물고기라면, \n너도 나와 같은 바다의 아이일 테니.”\n2020 오늘..."
2456,9788936443160,푸른 사자 와니니 3 3,이현,NaN,8.0,검은 땅의 평화를 되찾기 위한 \n와니니와 친구들의 감동적인 모험\n‘푸른 사자 와...

In [ ]:
s_list[s_list['상품명'].map(lambda x: '일의' in x)]

Empty DataFrame
Columns: [상품코드, 상품명, 인물, 분야, 분류기호, 책 소개]
Index: []

In [ ]:
s_list.loc[2296,'책 소개']

'평범한 일상을 꿈꿀수록 사람들 앞에 나설 수밖에 없는 수수께끼와 조우하게 되는 여우와 늑대!\n\n학교를 배경으로 일상의 사건들을 다룬 「고전부 시리즈」와 함께 요네자와 호노부의 대표 시리즈로 꼽히는 학원 청춘 미스터리 「소시민 시리즈」의 세 번째 이야기 『가을철 한정 구리킨톤 사건』 하권. 《여름철 한정 트로피컬 파르페 사건》에서 함께 있으면 소시민이 될 수 없다며 서로에게 이별을 고했던 교활한 여우 고바토와 음흉한 늑대 오사나이. 이번 작품은 고바토와 오사나이의 관계에 대한 궁금증이 이야기를 끌고 나간다. \n\n두 사람이 헤어진 뒤 새롭게 등장한 인물은, 자신은 굉장한 사람이며 언젠가 큰일을 해낼 거라는 생각을 가지고 있지만 능력은 평범한, 전형적인 소시민에 가까운 우리노다. 우리노가 고등학교 생활에 자신의 흔적을 남기고자 하는 자연스러운 행위는 어느 순간 위험한 선을 넘나든다. 고바토와 새로운 인물 우리노가 각자의 관점에서 연쇄 방화 사건을 좇는 모습을 그리고 있는 이 작품은 사건을 통해 명탐정의 지위를 겨루는, 일종의 우월성을 가리는 게임을 한다고도 볼 수 있다. 자신의 실력을 과신하고 남들의 주목을 갈구하는 우리노의 모습은 고바토가 중학교 시절 경험한 깊은 좌절을 연상시킨다.\n\n참견하기 좋아하는 고바토와 집념이 강한 오사나이는 공통의 목표를 가진 특별한 관계로 묶여 있다. 그것은 바로 일상의 평온과 안정을 위해 소시민의 길을 추구하는 것! 하지만 일련의 사건을 겪으며 두 사람은 헤어지게 된다. 한편 마을에서는 방화 사건이 일어나고, 사건을 다룬 교내 신문의 기사가 화제가 된다. 이 사건 어쩐지 수상한데…….'

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='일의 기쁨과 슬픔']

,상품코드,상품명,인물,분야,분류기호,책 소개
390,9788936438036,일의 기쁨과 슬픔,장류진,소설,NaN,"모두가 기억하게 될 이름, 장류진이 전하는 오늘의 이야기!\n\n2018년 창비신인..."

In [ ]:
# seoul 데이터 책 이름이랑 왓챠피디아 책 이름 통일하기 (수작업)
seoul.loc[676, '상품명'] = '재수사'
seoul.loc[700, '상품명'] = '레슨 인 케미스트리'
seoul.loc[723, '상품명'] = '빨치산의 딸'
seoul.loc[733, '상품명'] = '안락 탐정'
seoul.loc[743, '상품명'] = '재벌집 막내아들'
seoul.loc[747, '상품명'] = '클론 게임'
seoul.loc[765, '상품명'] = '기사단장 죽이기'
seoul.loc[790, '상품명'] = '수확자'
seoul.loc[791, '상품명'] = '술꾼도시처녀들'
seoul.loc[811, '상품명'] = '체리새우 : 비밀글입니다'
seoul.loc[815, '상품명'] = '해리 포터와 마법사의 돌'
seoul.loc[819, '상품명'] = '엽기 과학자 프래니'
seoul.loc[973, '상품명'] = '1Q84'
seoul.loc[842, '상품명'] = '깊은 밤 필통 안에서'
seoul.loc[843, '상품명'] = '꾸뻬 씨의 행복 여행'
seoul.loc[844, '상품명'] = '나를 보내지 마'
seoul.loc[855, '상품명'] = '데카메론'
seoul.loc[861, '상품명'] = '로드 짐'
seoul.loc[872, '상품명'] = '미들마치'
seoul.loc[873, '상품명'] = '미키7'
seoul.loc[1188, '상품명'] = '십이국기'
seoul.loc[878, '상품명'] = '변신 이야기'
seoul.loc[900, '상품명'] = '심야식당'
seoul.loc[905, '상품명'] = '안드로이드는 전기양의 꿈을 꾸는가?'
seoul.loc[924, '상품명'] = '잃어버린 시간을 찾아서'
seoul.loc[926, '상품명'] = '자기 앞의 생'
seoul.loc[927, '상품명'] = '작은 집 이야기'
seoul.loc[939, '상품명'] = '카라마조프가의 형제들'
seoul.loc[945, '상품명'] = '파리의 도서관'
seoul.loc[958, '상품명'] = '오베라는 남자'
seoul.loc[968, '상품명'] = '녹정기'
seoul.loc[969, '상품명'] = '신곡 - 연옥편'
seoul.loc[970, '상품명'] = '신곡 - 지옥편'
seoul.loc[978, '상품명'] = '해리 포터와 죽음의 성물'
seoul.loc[982, '상품명'] = '거미여인의 키스'
seoul.loc[985, '상품명'] = '기술복제시대의 예술작품 / 사진의 작은 역사 외'
seoul.loc[1004, '상품명'] = '당신, 거기 있어 줄래요?'
seoul.loc[1017, '상품명'] = '랑야방'
seoul.loc[1177, '상품명'] = '밤 여행자'
seoul.loc[1026, '상품명'] = '삼체'
seoul.loc[1028, '상품명'] = '셜록 홈즈의 모험'
seoul.loc[1048, '상품명'] = '위키드'
seoul.loc[1050, '상품명'] = '의천도룡기'
seoul.loc[1053, '상품명'] = '일곱 번째 아들 1'
seoul.loc[1739, '상품명'] = '제3인류'
seoul.loc[1063, '상품명'] = '죄와 벌'
seoul.loc[1070, '상품명'] = '천룡팔부'
seoul.loc[1078, '상품명'] = '파우스트'
seoul.loc[1083, '상품명'] = '해리 포터와 비밀의 방'
seoul.loc[1084, '상품명'] = '환야'
seoul.loc[1091, '상품명'] = '설민석의 삼국지'
seoul.loc[1104, '상품명'] = '달콤한 노래'
seoul.loc[1108, '상품명'] = '가난한 사람들'
seoul.loc[1154, '상품명'] = '돈키호테'
seoul.loc[1161, '상품명'] = '람세스'
seoul.loc[1172, '상품명'] = '몬테크리스토 백작'
seoul.loc[1192, '상품명'] = '인소의 법칙'
seoul.loc[1217, '상품명'] = '우리가 볼 수 없는 모든 빛'
seoul.loc[1227, '상품명'] = '시노부 선생님, 안녕'
seoul.loc[1238, '상품명'] = '명탐정 셜록 홈즈'
seoul.loc[1252, '상품명'] = '여자 제갈량'
seoul.loc[1254, '상품명'] = '시리아의 늑대'
seoul.loc[1261, '상품명'] = '중쇄를 찍자'
seoul.loc[1270, '상품명'] = '그레이'
seoul.loc[1286, '상품명'] = '시 읽는 밤 : 시 밤'
seoul.loc[1318, '상품명'] = '커피 한 잔 할까요?'
seoul.loc[1320, '상품명'] = '월드 오브 워크래프트 스랄 : 위상들의 황혼'
seoul.loc[1352, '상품명'] = '자전거여행'
seoul.loc[1428, '상품명'] = '어쿠스틱 라이프'
seoul.loc[1436, '상품명'] = '진달래꽃'
seoul.loc[1443, '상품명'] = 'The Book 더 북'
seoul.loc[1454, '상품명'] = '앵화연담'
seoul.loc[1469, '상품명'] = '아도니스'
seoul.loc[1486, '상품명'] = '이상한 나라의 앨리스'
seoul.loc[1489, '상품명'] = '은하철도의 밤'
seoul.loc[1491, '상품명'] = '겨울 가면 봄이 오듯, 사랑은 또 온다'
seoul.loc[1517, '상품명'] = '나의 투쟁'
seoul.loc[1520, '상품명'] = '더불어숲'
seoul.loc[1543, '상품명'] = '초판본 사슴'
seoul.loc[1588, '상품명'] = '루미너리스'
seoul.loc[1626, '상품명'] = '후와후와'
seoul.loc[1675, '상품명'] = '2016 제7회 젊은작가상 수상작품집'
seoul.loc[1711, '상품명'] = '줄리아, 어디에 있니?'
seoul.loc[1774, '상품명'] = '군함도'
seoul.loc[1780, '상품명'] = '내 손으로, 교토 + 오사카'
seoul.loc[1821, '상품명'] = '레몬첼로 도서관 : 탈출 게임'
seoul.loc[1827, '상품명'] = '딸바보가 그렸어, 엄마의 일기장'
seoul.loc[1843, '상품명'] = '왕좌의 게임'
seoul.loc[1840, '상품명'] = '디어 마이 프렌즈'
seoul.loc[1850, '상품명'] = '풀꽃도 꽃이다'
seoul.loc[1918, '상품명'] = '싸드 THAAD'
seoul.loc[1959, '상품명'] = '데미안'
seoul.loc[1960, '상품명'] = '구르미 그린 달빛'
seoul.loc[2025, '상품명'] = '고구려'
seoul.loc[2045, '상품명'] = '솔미솔파, 나의 노래'
seoul.loc[2054, '상품명'] = '해리 포터와 저주받은 아이'
seoul.loc[2061, '상품명'] = '교룡의 주인'
seoul.loc[2082, '상품명'] = '홍천기'
seoul.loc[2111, '상품명'] = '어쩌면 별들이 너의 슬픔을 가져갈지도 몰라 +플러스'
seoul.loc[2147, '상품명'] = '너의 저녁에 나를'
seoul.loc[2168, '상품명'] = '토니와 수잔 (영화 포스터 표지)'
seoul.loc[2205, '상품명'] = '베아트리체'
seoul.loc[2260, '상품명'] = '2017 제8회 젊은작가상 수상작품집'
seoul.loc[2268, '상품명'] = '베를린 누아르 1 - 3월의 제비꽃 (북스피어X)'
seoul.loc[2289, '상품명'] = '여우가 잠든 숲'
seoul.loc[2295, '상품명'] = '가을철 한정 구리킨톤 사건 - 상'
seoul.loc[2312, '상품명'] = '삼국지 조조전'
seoul.loc[2329, '상품명'] = '기억술사'
seoul.loc[2348, '상품명'] = '로스트 헤븐'
seoul.loc[2351, '상품명'] = '잠'
seoul.loc[2374, '상품명'] = '수인'
seoul.loc[2396, '상품명'] = '보복대행전문주식회사'
seoul.loc[2404, '상품명'] = '토지'
seoul.loc[2446, '상품명'] = '시크THICK'
seoul.loc[2447, '상품명'] = '엄마 박완서의 부엌 : 정확하고 완전한 사랑의 기억'
seoul.loc[2486, '상품명'] = '소설 보다 : 봄'
seoul.loc[2532, '상품명'] = '소설 보다 : 여름'
seoul.loc[2549, '상품명'] = '명랑한 은둔자'

In [ ]:
seoul

,상품코드,상품명,인물,분야,분류기호,책 소개
642,9788970129815,파친코 1,이민진,NaN,8.0,어디에도 속하지 못했던 자이니치들의 분노와 슬픔에서 탄생한 대작!\n\n한국계 1....
651,9788949162126,달콩이네 떡집,김리리,NaN,8.0,80만 부 돌파!\n초등 3학년 국어 교과서 수록 \n「만복이네 떡집」 시리즈 최신...
655,9788954681155,홍학의 자리,정해연,NaN,8.0,“이 행복이 영원할 거라고 생각한 적은 없었다.\n그러나 이런 끝을 상상한 적도 없...
656,9788997962129,망원동 브라더스,김호연,NaN,8.0,"상처받은 이들이여, 연체된 인생들이 모여 사는 8평 옥탑방으로 오라!\n\n김호연의..."
658,9788925588735,프로젝트 헤일메리,앤디 위어,NaN,8.0,“이름도 기억 못하는 내가 인류의 희망이라니?”\n멸망 위기의 지구 구하기 프로젝트...
...,...,...,...,...,...,...
2607,9791189336462,헌책방 기담 수집가,윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
2608,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
2609,9791159257117,클락워크 도깨비,황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...
2610,9791136748195,비밀 THE TOP SECRET season0,Reiko Shimizu,NaN,8.0,"준이치로부터 마이를 구해낸 히카루, 그리고 히카루를 진심으로 믿고 싶은 아오키."
2611,9788986022476,한그루 열두 가지,박정미,NaN,8.0,도시생활자의 마음밭에 심어보는\n일 년 열두 가지 작물\n\n공방 ‘달실’ 김기란 ...

In [ ]:
# 없는 책 목록 골라내기
seoul_list = book_rating[book_rating['book'].map(lambda x: x in list(seoul['상품명']))]

In [ ]:
len(seoul_list['book'].unique())

836

In [ ]:
seoul_list

                 user           book  book_ID  rating
0       8nPvyyWmovYo0  해리 포터와 마법사의 돌  boYDGk4     3.0
1       8nPvyyWmovYo0           파리대왕  bowNK14     3.5
2       8nPvyyWmovYo0        지금 이 순간  boYOaR9     2.5
16      DgwxAeQYNxrMj     느리게 걷는 즐거움  b9R8Aam     3.5
56      DgwxAeQYNxrMj         칠드런 액트  byEjdj9     4.0
...               ...            ...      ...     ...
349726  17ovVzDWLvzyn   해리 포터와 비밀의 방  b4D3Qr9     3.5
349727  17ovVzDWLvzyn  해리 포터와 마법사의 돌  boYDGk4     4.0
349730  17ovVzDWLvzyn            탈무드  boweMVa     3.5
349734  17ovVzDWLvzyn          어린 왕자  bovqv5J     4.0
349756  17ovVzDWLvzyn    나의 라임 오렌지나무  byzeJko     5.0

[39922 rows x 4 columns]

In [ ]:
seoul_sel = seoul[seoul['상품명'].map(lambda x: x in list(seoul_list['book'].unique()))]
seoul_sel.reset_index(drop=True, inplace=True)
seoul_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9788949162126,달콩이네 떡집,김리리,NaN,8.0,80만 부 돌파!\n초등 3학년 국어 교과서 수록 \n「만복이네 떡집」 시리즈 최신...
1,9788954681155,홍학의 자리,정해연,NaN,8.0,“이 행복이 영원할 거라고 생각한 적은 없었다.\n그러나 이런 끝을 상상한 적도 없...
2,9788997962129,망원동 브라더스,김호연,NaN,8.0,"상처받은 이들이여, 연체된 인생들이 모여 사는 8평 옥탑방으로 오라!\n\n김호연의..."
3,9788925588735,프로젝트 헤일메리,앤디 위어,NaN,8.0,“이름도 기억 못하는 내가 인류의 희망이라니?”\n멸망 위기의 지구 구하기 프로젝트...
4,9788954677158,긴긴밤,루리,NaN,8.0,제21회 문학동네어린이문학상 대상 수상작 『긴긴밤』\n\n세상에 마지막 하나 남은 ...
...,...,...,...,...,...,...
849,9791192097060,소마,채사장,NaN,8.0,"※양장본 리커버 에디션: 매장 구매, 바로드림 구매 시에는 일반판 랜덤으로 제공됩니..."
850,9791159257100,얼음 속의 엄마를 떠나보내다,남유하,NaN,8.0,한낙원과학소설상 수상ㆍ과학소재공모전 우수상에 수상 빛나는 작가. 남유하의 판타지 고...
851,9791189336462,헌책방 기담 수집가,윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
852,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
853,9791159257117,클락워크 도깨비,황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...

In [ ]:
# 추출된 책 평점 데이터에서 (user, book) 중복되는 데이터 선택
seoul_list[seoul_list.duplicated(subset=['user','book'])]['book'].unique()

array(['일의 기쁨과 슬픔', '칼의 노래', '멋진 신세계', '덕혜옹주', '변신', '토지', '젊은 베르테르의 슬픔',
       '동급생', '앵무새 죽이기', '소설 보다 : 여름', '작은 아씨들', '한국이 싫어서', '이상한 나라의 앨리스',
       '노인과 바다', '한여름 밤의 꿈', '이방인', '너의 췌장을 먹고 싶어', '랑야방', '고래', '라마야나',
       '청춘 돼지는 바니걸 선배의 꿈을 꾸지 않는다', '어린 왕자', '디어 마이 프렌즈', '몬테크리스토 백작', '잠',
       '파우스트', '기억술사', '데카메론', '사자왕 형제의 모험', '섬', '돈키호테', '황제의 외동딸',
       '나는 왜 너가 아니고 나인가', '첫사랑', '아몬드', '단테의 신곡', '탈무드', '서랍에 저녁을 넣어 두었다',
       '초속 5센티미터', '하늘과 바람과 별과 시', '해리 포터와 비밀의 방', '할로우 시티', '아리랑',
       '해리 포터와 죽음의 성물', '가난한 사람들', '당신, 거기 있어 줄래요?', '달의 조각', '제5도살장',
       '밤이 선생이다', '소설 보다 : 봄', '백석 평전', '사랑의 역사', '고구려', '자기만의 방'],
      dtype=object)

In [ ]:
seoul_list[seoul_list['book']=='나는 왜 너가 아니고 나인가']

                 user             book  book_ID  rating
4360    6ewxadmOe5Q1m  나는 왜 너가 아니고 나인가  boYrPQR     4.0
46605   VRZv4ePYE15r6  나는 왜 너가 아니고 나인가  boYrPQR     3.5
75656   6ewxa0wl85Q1m  나는 왜 너가 아니고 나인가  b98KLnl     4.0
75659   6ewxa0wl85Q1m  나는 왜 너가 아니고 나인가  b98KLnl     4.0
95738   7gdxdkJZE5GYJ  나는 왜 너가 아니고 나인가  b98KLnl     5.0
117412  7gdxdr7e9vGYJ  나는 왜 너가 아니고 나인가  boYrPQR     5.0
122211  Pznx9Kmk2Zv76  나는 왜 너가 아니고 나인가  boYrPQR     3.0
160071  g64qznJD1qER0  나는 왜 너가 아니고 나인가  b98KLnl     4.5
160216  g64qznJD1qER0  나는 왜 너가 아니고 나인가  b98KLnl     4.5
291476  Jgkql1MLnvX0b  나는 왜 너가 아니고 나인가  b98KLnl     3.0
292425  Jgkql1MLnvX0b  나는 왜 너가 아니고 나인가  b98KLnl     3.5

In [ ]:
seoul_list[seoul_list['book']=='자기만의 방']['book_ID'].unique()

array(['bovdKxP'], dtype=object)

In [ ]:
# 이름만 같은 완전 다른 책 목록
book_list1_seoul = ['칼의 노래','덕혜옹주','변신','토지','동급생','앵무새 죽이기','소설 보다 : 여름','라마야나', '잠','파우스트',
                    '나는 왜 너가 아니고 나인가','첫사랑','초속 5센티미터','아리랑','가난한 사람들','소설 보다 : 봄','백석 평전',
                    '사랑의 역사','고구려']

In [ ]:
# 버릴 책 목록
rem_list_seoul = ['byLwbao','b9nKZlp', 'b9WD8ma','byXrKk6','boGQ8v9','b9JgN7k','boYdbYg', 'byZ5R18','byzG1lk','byXrANE','b98NwNQ',
                  'b9n6z89','bogaB19', 'byEr8dL','byz7Xn9','boYrPQR','boOKaro', 'byzG7e0', 'b98Kwq2', 'boqZdmy', 'b4eb8lo',
                  'byX00Zy', 'byVebqM', 'b981j54', 'byL0lA3', 'b4DA1Z8','bymBJZx','b4MOmXk', 'boNKzkO','bo50J57','b98Nx8X',
                  'boNKlPj','boGEK89','b401eZv', 'boON5n4','byVeARM', 'boGWJY8','bo3AOYY']

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='삼체']

Empty DataFrame
Columns: [상품코드, 상품명, 인물, 분야, 분류기호, 책 소개]
Index: []

In [ ]:
seoul_sel[seoul_sel['상품명']=='자기만의 방']

,상품코드,상품명,인물,분야,분류기호,책 소개
690,9788937429040,자기만의 방,버지니아 울프,NaN,8.0,‘지금 이곳’에 꼭 필요한 책을 만나다!\n\n1966년 창립된 출판사 민음사의 로...

In [ ]:
seoul_sel[seoul_sel['상품명']=='당신, 거기 있어 줄래요?']['책 소개'].values

array(["30년 전, 첫사랑을 만날 기회가 주어진다!\n\n《구해줘》의 작가 기욤 뮈소의 최신 장편소설『당신 거기 있어줄래요』. '만약 우리에게 시간을 되돌릴 기회가 주어진다면, 인생을 어떻게 바꿀 것인가?'라는 질문을 던지는 이 책은 시간의 개념과 인생의 선택에 대한 성찰의 기회 제공이라는 두 가지 요소를 생생한 화면 구성, 빠른 전개로 결합시켜 독특하게 그려내고 있다. \n\n주인공 엘리엇은 명망 있는 외과의사로 성공적인 삶을 열어왔지만 한 가지 떨쳐버릴 수 없는 회한이 있다. 그것은 바로 사랑하는 연인을 사고로부터 구해내지 못한 것이다. \n\n캄보디아에서 만난 신비의 노인으로부터 과거로 돌아갈 수 있는 열 개의 알약을 얻게 된 그는 30년 전으로 돌아갈 수 있는 기회를 부여잡는다. 그러나 죽은 일리나를 살려내면서 그의 삶은 예기치 못한 대혼란의 소용돌이 속으로 휩쓸려가는데….",
       '시간을 되돌릴 수 있는 기회가 주어진다면 \n당신은 사랑을, 인생을 어떻게 바꿀 것인가?\n\n인생의 운명을 바꾸기 위해 떠나는 사랑의 시간여행! 한국 영화로 탄생한 기욤 뮈소 소설!'],
      dtype=object)

In [ ]:
# seoul_list에서 삭제할 책
seoul_list.drop(seoul_list[seoul_list['book']=='일의 기쁨과 슬픔'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='멋진 신세계'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='작은 아씨들'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='이방인'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='너의 췌장을 먹고 싶어'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='고래'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='청춘 돼지는 바니걸 선배의 꿈을 꾸지 않는다'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='어린 왕자'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='섬'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='황제의 외동딸'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='아몬드'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='우리 딸을 위해서라면, 나는 마왕도 쓰러뜨릴 수 있을지 몰라 3'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='여름과 연기'].index, inplace=True)

In [ ]:
# 책 목록 중복 확인
seoul_sel[seoul_sel.duplicated('상품명')]

,상품코드,상품명,인물,분야,분류기호,책 소개
59,9788936456788,아몬드,손원평,NaN,8.0,"공감 불능 사회, 차가움을 녹이는 아몬드\n매혹적인 문체, 독특한 캐릭터, 속도감 ..."
154,9781476738017,오베라는 남자,프레드릭 배크만,NaN,8.0,"30초마다 웃음이 터지는 시한폭탄 같은 소설\n시종일관 유쾌하고, 불현듯 감동적인 ..."
186,9788984374409,"당신, 거기 있어 줄래요?",기욤 뮈소,NaN,8.0,"시간을 되돌릴 수 있는 기회가 주어진다면 \n당신은 사랑을, 인생을 어떻게 바꿀 것..."
187,9791188345007,데미안,헤르만헤세,NaN,8.0,헤르만 헤세는 1877년 독일 뷔르템베르크의 칼프에서 태어나 1890년 라틴어 학교...
188,9791157771080,데미안,헤르만헤세,NaN,8.0,불안한 젊음에 바치는 헤르만 헤세의 영혼의 이야기!\n\n『데미안』은 자신의 세계를...
202,9788954439923,삼체,류츠신,NaN,8.0,중국 SF 3대 천왕으로 불리는 류츠신의 대표작!\n\n「지구의 과거」 3부작의 마...
225,9791189660291,카라마조프가의 형제들,도스토예프스키,NaN,8.0,"표도르 파블로비치 카라마조프는 러시아의 한 소도시에 사는 지주로, 그에게는 네 명의..."
352,9788937460616,설국,가와바타 야스나리,NaN,8.0,1968년 노벨상 수상작 이 정식 계약을 통해 출판되었다. 일본 문학사상 최고의 서...
416,9788998046651,이상한 나라의 앨리스,루이스 캐럴,NaN,8.0,초판본 디자인으로 만나는 이상한 나라의 앨리스!\n\n1866년에 발행된 초판본을 ...
419,9788982816635,자기 앞의 생,에밀 아자르,NaN,8.0,전 세계에 파문을 던진 아자르의 충격!\n\n열네 살 소년 모모가 들려주는 신비롭고...
461,9788998046705,하늘과 바람과 별과 시,윤동주,NaN,8.0,"일제의 탄압이 극에 달하고 한국어 사용과 창작이 금지되었던 1941년, 윤동주는 우..."
464,9791159030567,하늘과 바람과 별과 시,윤동주,NaN,8.0,고전 중에서도 세계적으로 문학적 가치를 인정받고 시대를 뛰어 넘어 사랑받는 작품들을...
525,9788961592611,동급생,아스미코 나카무라,NaN,8.0,노골적이진 않지만 은근하기에 더욱 매력적인 두 사람의 애틋하고 사랑스러운 러브스토리...
599,9791159031076,데미안,헤르만헤세,NaN,8.0,헤르만 헤세가 1919년 ‘에밀 싱클레어’라는 가명으로 출판한 소설『데미안』을 오리...
620,9791126436668,황제의 외동딸,리노 (만화)^윤슬,NaN,8.0,*포장 비닐 손상 후 파손 및 누락 물품 교환/환불 불가. \n특전의 개수와 상태를...
655,9788932318264,나 안 괜찮아,실키,NaN,8.0,"『나 안 괜찮아 리미티드 에디션』은 [나 안 괜찮아] 리커버 도서와 에스프레소잔, ..."
699,9791127840488,"우리 딸을 위해서라면, 나는 마왕도 쓰러뜨릴 수 있을지 몰라 3",CHIROLU,NaN,8.0,"『우리 딸을 위해서라면, 나는 마왕도 쓰러뜨릴 수 있을지 몰라』 제3권. 청순가련하..."
826,9791166890246,명랑한 은둔자,캐롤라인 냅,NaN,8.0,"캐럴라인 냅은 지적이고 유려한 회고록 성격의 에세이를 쓴 작가로, 2002년 마흔둘..."

In [ ]:
seoul_sel[seoul_sel['상품명']=='섬']

,상품코드,상품명,인물,분야,분류기호,책 소개
368,9791131936764,섬,하늘가리기,NaN,8.0,"하늘가리기 장편소설 『섬』. 나는 너를 한눈에 알아봤는데. 우연한 만남, 우연한 사..."

In [ ]:
seoul_sel[seoul_sel['상품명']=='명랑한 은둔자']['책 소개'].values

array(['“나는 명랑한 은둔자야.”\n고독의 즐거움, 고립의 괴로움을\n우아하게, 솔직하게, 유머러스하게 말하는 지적인 목소리\n\n『명랑한 은둔자』는 캐럴라인 냅의 유고 에세이집으로, 캐럴라인 냅이라는 작가의 삶 전반을 빼곡히 담고 있는 초상과 같은 책이다. 캐럴라인 냅은 삶의 미스터리가 크든 작든 그 모두를 예민하게 살피고, 무엇보다 거기서 자기 이해를 갈망했던 작가다. 그는 이 에세이에서 혼자 살고 혼자 일했고, 가족과 친구와 개와 소중한 관계를 맺으며 자기 앞의 고독을 외면하지 않았던 삶을 이야기한다. 또한 알코올과 거식증에 중독되었으나 그로부터 힘겹게 빠져나왔고, 그 과정에서 자신을 옥죄었던 심리적 굴레를 벗어나 자유와 해방감을 경험한 한 인간의 깨달음을 들려준다. \n\n캐럴라인 냅의 삶을 설명할 수 있는 키워드는 다음과 같이 정리할 수 있다. 중독, 결핍, 가족, 반려견, 우정, 사랑, 애착, 일, 성장, 슬픔, 상실, 고립, 고독……. 특히 중독은 냅의 삶에서 빠질 수 없는 키워드다. 그는 알코올 중독과 거식증을 겪으면서 자신이 어디까지 추락할 수 있는지 보았고, 그 까마득한 어둠으로부터 빠져나오기 위해 다시 한 번 자기 자신과 정면으로 맞서는 시간을 보냈다. 누구보다 캐럴라인 냅의 삶을 깊이 이해하고 있는 옮긴이 김명남의 말처럼, 냅은 자기 이해와 수용, 그리고 변화에 관해 이야기하려고 애썼고, 더 자유롭고, 더 즐겁고, 더 자신다운 사람이 되기 위해 희망의 끈을 놓지 않았다. 자신의 강함과 약함을 있는 그대로 받아들이면서 결국 삶의 명랑을 깨달은 저자로부터, 우리는 만난 적 없지만 오래 이어온 듯한 우정을 느낄 수 있을 것이다. 냅의 이야기는 내 이야기 같고, 내 친구 이야기 같다. 이것이 냅의 재능이고, 그의 글이 가진 힘이다.',
       '캐럴라인 냅은 지적이고 유려한 회고록 성격의 에세이를 쓴 작가로, 2002년 마흔둘이라는 이른 나이에 세상을 떠났다. 냅은 살면서 몇몇 끔찍한 중독에 빠진 경험이 있는데, 삶의 불가사의한 두려움으로부터 달아나고 싶을 땐 술로, 그런 자기 자신을 호되게 통제하고 싶을 땐 음식을 거부했다. 그는 이런 자신의 깊은 내면 이야기를 솔직하게, 우아하게, 또렷하게 고백해 세상을 놀라게 했다. 『드링킹, 그 치명적 유혹(Drinking)』은 알코올 중독의 삶을, 『세상은 왜 날씬한 여자를 원하는가(Appetites)』는 다이어트 강박증과 섭식장애에 관한 기록이다. 개를 향한 지나친 애착이 염려스러울 정도로 개를 사랑하여 그 마음을 『남자보다 개가 더 좋아(Pack of Two)』라는 책에 담기도 했다.\n\n『명랑한 은둔자』는 그의 유고 에세이집으로, 캐럴라인 냅이라는 작가의 삶 전반을 빼곡히 담고 있는 초상과 같은 책이다.'],
      dtype=object)

In [ ]:
# 책소개 NaN 확인 => 삭제
seoul_sel[seoul_sel['책 소개'].isna()]

              상품코드     상품명        인물   분야  분류기호 책 소개
129  9788937462665     이방인    알베르 카뮈  NaN   8.0  NaN
211  9788955061604  여름과 연기  테네시 윌리엄즈  NaN   8.0  NaN

In [ ]:
# 시리즈물/중복되는 책 하나만 남기기
seoul_sel.drop([218], inplace=True) # 일의 기쁨과 슬픔
seoul_sel.drop([54], inplace=True) # 멋진 신세계
seoul_sel.drop([525], inplace=True) # 동급생
seoul_sel.drop([68], inplace=True) # 작은 아씨들
seoul_sel.drop([129], inplace=True) # 이방인
seoul_sel.drop([211], inplace=True) # 여름과 연기
seoul_sel.drop([717], inplace=True) # 너의 췌장을 먹고 싶어
seoul_sel.drop([45], inplace=True) # 고래
seoul_sel.drop([400], inplace=True) # 청춘 돼지는...
seoul_sel.drop([371], inplace=True) # 어린 왕자
seoul_sel.drop([368], inplace=True) # 섬
seoul_sel.drop([497,620], inplace=True) # 황제의 외동딸
seoul_sel.drop([27,59], inplace=True) # 아몬드
seoul_sel.drop([439,464], inplace=True) # 하늘과 바람과 별과 시
seoul_sel.drop([186], inplace=True) # 당신, 거기 있어 줄래요?

seoul_sel.drop([30], inplace=True) # 오베라는 남자
seoul_sel.drop([90,187,599], inplace=True) # 데미안
seoul_sel.drop([109], inplace=True) # 삼체
seoul_sel.drop([141], inplace=True) # 카라마조프가의 형제들
seoul_sel.drop([352], inplace=True) # 설국
seoul_sel.drop([298], inplace=True) # 이상한 나라의 앨리스
seoul_sel.drop([133], inplace=True) # 자기 앞의 생
seoul_sel.drop([655], inplace=True) # 나 안 괜찮아
seoul_sel.drop([698,699], inplace=True) # 우리 딸을 위해서라면, 나는 마왕도 쓰러뜨릴 수 있을지 몰라 3
seoul_sel.drop([826], inplace=True) # 명랑한 은둔자

In [ ]:
seoul_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9788949162126,달콩이네 떡집,김리리,NaN,8.0,80만 부 돌파!\n초등 3학년 국어 교과서 수록 \n「만복이네 떡집」 시리즈 최신...
1,9788954681155,홍학의 자리,정해연,NaN,8.0,“이 행복이 영원할 거라고 생각한 적은 없었다.\n그러나 이런 끝을 상상한 적도 없...
2,9788997962129,망원동 브라더스,김호연,NaN,8.0,"상처받은 이들이여, 연체된 인생들이 모여 사는 8평 옥탑방으로 오라!\n\n김호연의..."
3,9788925588735,프로젝트 헤일메리,앤디 위어,NaN,8.0,“이름도 기억 못하는 내가 인류의 희망이라니?”\n멸망 위기의 지구 구하기 프로젝트...
4,9788954677158,긴긴밤,루리,NaN,8.0,제21회 문학동네어린이문학상 대상 수상작 『긴긴밤』\n\n세상에 마지막 하나 남은 ...
...,...,...,...,...,...,...
849,9791192097060,소마,채사장,NaN,8.0,"※양장본 리커버 에디션: 매장 구매, 바로드림 구매 시에는 일반판 랜덤으로 제공됩니..."
850,9791159257100,얼음 속의 엄마를 떠나보내다,남유하,NaN,8.0,한낙원과학소설상 수상ㆍ과학소재공모전 우수상에 수상 빛나는 작가. 남유하의 판타지 고...
851,9791189336462,헌책방 기담 수집가,윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
852,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
853,9791159257117,클락워크 도깨비,황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...

In [ ]:
len(seoul_list['book'].unique())

823

In [ ]:
# kyobo_sel이랑 seoul_sel에 겹치는 책 확인 (상품명 중복)
df_cat_title = pd.concat([kyobo_sel, seoul_sel])
df_cat_title[df_cat_title.duplicated('상품명')]

,상품코드,상품명,인물,분야,분류기호,책 소개
20,9788954619592,단순한 열정,아니 에르노,NaN,8.0,『아니 에르노 단순한 열정』은 한 여인의 범상치 않은 사랑 이야기다. 주인공은 한 ...
24,9788954622035,살인자의 기억법,김영하,NaN,8.0,정교하게 다듬어진 공포의 기록!\n\n김영하의 장편소설 『살인자의 기억법』. 《너의...
38,9788936434540,피프티 피플,정세랑,NaN,8.0,『피프티 피플』 10만부 판매 기념 전면개정판 출간! \n50명의 손을 하나하나 맞...
188,9791157771080,데미안,헤르만헤세,NaN,8.0,불안한 젊음에 바치는 헤르만 헤세의 영혼의 이야기!\n\n『데미안』은 자신의 세계를...
512,9788954640718,흰,한강,NaN,8.0,"결코 더럽혀지지 않는, 절대로 더럽혀질 수가 없는 어떤 흰 것에 관한 이야기!\n\..."
652,9788937433818,노르웨이의 숲,무라카미 하루키,NaN,8.0,30주년을 기념해 새로운 표지로 만나는 『노르웨이의 숲』!\n\n1987년 초판을 ...

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='노르웨이의 숲']

,상품코드,상품명,인물,분야,분류기호,책 소개
150,9788937434488,노르웨이의 숲,무라카미 하루키,소설,NaN,무라카미 하루키를 만나기 위해 가장 먼저 읽어야 할 책\n\n무라카미 하루키의 대표...

In [ ]:
kyobo_sel[kyobo_sel['상품명']=='노르웨이의 숲']['책 소개'].values

array(['무라카미 하루키를 만나기 위해 가장 먼저 읽어야 할 책\n\n무라카미 하루키의 대표작 『노르웨이의 숲』. 1987년 발표된 후 세계적인 ‘하루키 붐’을 일으키며 저자의 문학적 성과를 널리 알린 현대 일본 문학의 대표작이다. 원문에 충실하면서도 현대적인 언어로 새롭게 번역한 이 책은 첫 만남을 추억하는 독자와 새로운 만남을 기다리는 독자 모두에게 잊지 못할 기억을 전해준다.\n\n독일 함부르크 공항에 막 착륙한 비행기 안에서 울린 비틀스의 《노르웨이의 숲》을 듣고 와타나베는 자신에게 간절한 부탁을 남긴 여자와 그 부탁을 떠올린다. 고등학교 시절 친한 친구 기즈키, 그의 여자 친구 나오코와 언제나 함께였던 와타나베. 그러나 기즈키의 갑작스러운 자살로 행복한 시간은 끝나 버리고 만다. 도쿄의 사립대학에 진학해 고향을 떠나온 와나타베는 나오코와 한동안 연락을 끊고 지내던 어느 날, 자신이 요양원에 들어가 있다는 나오코의 편지를 받게 되는데…….'],
      dtype=object)

In [ ]:
seoul_sel[seoul_sel['상품명']=='노르웨이의 숲']

,상품코드,상품명,인물,분야,분류기호,책 소개
652,9788937433818,노르웨이의 숲,무라카미 하루키,NaN,8.0,30주년을 기념해 새로운 표지로 만나는 『노르웨이의 숲』!\n\n1987년 초판을 ...

In [ ]:
seoul_sel[seoul_sel['상품명']=='노르웨이의 숲']['책 소개'].values

array(['30주년을 기념해 새로운 표지로 만나는 『노르웨이의 숲』!\n\n1987년 초판을 재해석한 디자인으로 팬들의 마음을 사로잡을, 단 하나의 한정판 『노르웨이의 숲(30th 기념 리미티드 에디션)』. 1987년 처음 세상에 소개된 이래 36개국 이상에서 번역 출간되며 전 세계적으로 하루키 붐을 일으킨 책이다. 저자가 직접 지정한 것으로 잘 알려진 강렬한 레드와 그린 컬러 표지를 세월의 아련한 베일 너머 떠오르도록 재해석한 디자인으로 오랜 기다림 끝에 팬들 곁을 찾은 아주 특별한 리미티드 에디션이다. \n\n단절과 소통, 고독과 사랑, 과거와 기억, 삶과 죽음 등 인간이 살아가면서 직면하는 거의 모든 국면을 생생한 감성으로 묘사한 한 장의 소묘와도 같은 이 작품은 기성세대가 이끌어 낸 화려한 고도성장, 그리고 새로운 세대가 불러일으킨 저항 문화가 공존했던 1960년대 말 일본이라는 공간을 무대로 와타나베라는 젊은이의 시선을 통해 ‘사랑과 죽음’이라는, 개인의 삶 가운데 가장 중요한 문제를 정면에서 응시한다.\n\n독일 함부르크 공항에 막 착륙한 비행기 안에서 울린 비틀스의 《노르웨이의 숲》을 듣고 와타나베는 자신에게 간절한 부탁을 남긴 여자와 그 부탁을 떠올린다. 고등학교 시절 친한 친구 기즈키, 그의 여자 친구 나오코와 언제나 함께였던 와타나베. 그러나 기즈키의 갑작스러운 자살로 행복한 시간은 끝나 버리고 만다. 도쿄의 사립대학에 진학해 고향을 떠나온 와나타베는 나오코와 한동안 연락을 끊고 지내던 어느 날, 자신이 요양원에 들어가 있다는 나오코의 편지를 받게 되는데…….\n\n▶ 표지 이미지: 날개 커버가 있는 모습, 없는 모습을 함께 담은 모습으로 두 권이 아닌 한 권입니다.'],
      dtype=object)

In [ ]:
# 중복 책 삭제
kyobo_sel.drop([77], inplace=True) # 단순한 열정
kyobo_sel.drop([105], inplace=True) # 살인자의 기억법
seoul_sel.drop([38], inplace=True) # 피프티 피플
kyobo_sel.drop([331], inplace=True) # 데미안
seoul_sel.drop([512], inplace=True) # 흰
seoul_sel.drop([652], inplace=True) # 노르웨이의 숲

In [ ]:
# 책 평점 리스트에서 중복 책 삭제
new_book_rating.drop(new_book_rating[new_book_rating['book']=='단순한 열정'].index, inplace=True)
new_book_rating.drop(new_book_rating[new_book_rating['book']=='살인자의 기억법'].index, inplace=True)
new_book_rating.drop(new_book_rating[new_book_rating['book']=='데미안'].index, inplace=True)

seoul_list.drop(seoul_list[seoul_list['book']=='피프티 피플'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='흰'].index, inplace=True)
seoul_list.drop(seoul_list[seoul_list['book']=='노르웨이의 숲'].index, inplace=True)

In [ ]:
seoul_list.reset_index(drop=True, inplace=True)
seoul_list

                user           book  book_ID  rating
0      8nPvyyWmovYo0  해리 포터와 마법사의 돌  boYDGk4     3.0
1      8nPvyyWmovYo0           파리대왕  bowNK14     3.5
2      8nPvyyWmovYo0        지금 이 순간  boYOaR9     2.5
3      DgwxAeQYNxrMj     느리게 걷는 즐거움  b9R8Aam     3.5
4      DgwxAeQYNxrMj         칠드런 액트  byEjdj9     4.0
...              ...            ...      ...     ...
35416  17ovVzDWLvzyn       양과 강철의 숲  bop10Py     3.5
35417  17ovVzDWLvzyn   해리 포터와 비밀의 방  b4D3Qr9     3.5
35418  17ovVzDWLvzyn  해리 포터와 마법사의 돌  boYDGk4     4.0
35419  17ovVzDWLvzyn            탈무드  boweMVa     3.5
35420  17ovVzDWLvzyn    나의 라임 오렌지나무  byzeJko     5.0

[35421 rows x 4 columns]

In [ ]:
# 이름만 같은 완전 다른 책 평점 처리
rating_book1_seoul = pd.DataFrame()

for title in book_list1_seoul:
    df = seoul_list[seoul_list['book']==title]
    user = list(df[df.duplicated(subset='user')]['user'].values)
    user_df1 = df[df['user'].map(lambda x: x in user)]
    user_df2 = df[df['user'].map(lambda x: x not in user)]
    user_df1 = user_df1.drop_duplicates()
    user_df2 = user_df2[user_df2['book_ID'].map(lambda x: x not in rem_list_seoul)]
    new_df = pd.concat([user_df1, user_df2])
    rating_book1_seoul = pd.concat([rating_book1_seoul, new_df])

In [ ]:
# drop 안된 나머지 중복 책들에 대해 수작업
rating_book1_seoul[rating_book1_seoul.duplicated(['user','book'])][140:]

                user       book  book_ID  rating
7369   RE952eamEvQ72        첫사랑  boOO17o     4.0
10240  8BRveeyoDv6VJ        첫사랑  boOO17o     3.0
10932  8nPvyVZWo5Yo0        첫사랑  boOO17o     4.5
15604  2mwvggAE2vMa7        첫사랑  boOO17o     5.0
18314  8nPvygGwoxYo0        첫사랑  boOO17o     3.0
24989  YaR5YY04K5gX1        첫사랑  boOO17o     4.0
25628  JZ4vBkO7z5RXO        첫사랑  boOO17o     0.5
28297  6ewxa6RpWqQ1m  소설 보다 : 봄  bydlgQa     4.5
29484  a9L5PmwEPxwg8      백석 평전  boGEK89     3.0

In [ ]:
rating_book1_seoul[rating_book1_seoul['user']=='a9L5PmwEPxwg8']

                user   book  book_ID  rating
29495  a9L5PmwEPxwg8  칼의 노래  byEXbXa     1.5
29494  a9L5PmwEPxwg8     변신  bowr8Q4     5.0
29493  a9L5PmwEPxwg8   파우스트  byKmk54     4.5
29483  a9L5PmwEPxwg8  백석 평전  boGEK89     2.0
29484  a9L5PmwEPxwg8  백석 평전  boGEK89     3.0

In [ ]:
seoul_sel[seoul_sel['상품명']=='백석 평전']

,상품코드,상품명,인물,분야,분류기호,책 소개
533,9791130602769,백석 평전,안도현,NaN,8.0,"백석을 흠모하던 시인 안도현, 백석의 삶을 복원해내다!\n\n시대를 막론하고 절대적..."

In [ ]:
drop_idx_seoul = [587,3174,3656,4157,5645,6657,7399,10105,13444,14060,14411,15302,15491,15982,17043,17229,18240,18250,18468,18483,
                 18677,19408,21018,22000,23736,24356,25129,25308,25340,25401,25441,26966,27172,27668,28768,31126,32409,34071,35347,
                 215,768,964,966,4233,4464,4802,5062,5972,7669,7796,8364,9416,10324,12057,12326,13042,14550,15212,15347,16508,18289,
                 18481,18763,19087,21890,22200,22547,24013,24158,25111,25592,26213,26647,26870,26916,26967,27756,27891,27892,28650,
                 30010,30938,31855,32425,33977,34118,34133,35378,407,4014,4304,4651,9826,11898,13265,18627,18866,19077,22942,26122,
                 27049,29820,31672,33727,35338,1199,1242,1974,3805,7459,8363,9845,15865,29013,31071,31665,34129,1282,4079,4087,
                 6005,6346,6350,10188,10231,11667,21429,23701,23739,24734,26608,26618,32200,32209,34234,1445,6839,1550,10916,11285,
                 14170,14171,4311,5045,17313,28435,32905,29418,7369,10240,10932,15604,18314,24989,25628,28297,29483]

In [ ]:
rating_book1_seoul.drop(drop_idx_seoul, inplace=True)
rating_book1_seoul

                user   book  book_ID  rating
128    Pznx9aJ0Qx761  칼의 노래  byEXbXa     3.5
586    DgwxAB1oMqrMj  칼의 노래  byEXbXa     3.5
1177   VRZv4engZ5r6y  칼의 노래  byEXbXa     3.0
1188   JZ4vBQlmGqRXO  칼의 노래  byEXbXa     4.0
2085   YMKqmpDOyxloD  칼의 노래  byEXbXa     3.0
...              ...    ...      ...     ...
31531  D4WLxZKDZqroA    고구려  byzGkB8     4.0
32005  JgAx8zlb0vLbO    고구려  byzGkB8     3.5
33398  JgAx8XARAxLbO    고구려  byzGkB8     4.0
34727  4WLxZ8W1WvroA    고구려  byzGkB8     4.5
35322  Mr95nbp7d5ZPG    고구려  byzGkB8     3.5

[1950 rows x 4 columns]

In [ ]:
# 시리즈물/에디션/특별판 책 평점 처리
dup_book_seoul = list(seoul_list[seoul_list.duplicated(subset=['user','book'])]['book'].unique())
book_list2_seoul = [book for book in dup_book_seoul if book not in book_list1_seoul]
rating_book2_seoul = pd.DataFrame()

for title in book_list2_seoul:
    df = seoul_list[seoul_list['book']==title]
    user = list(df[df.duplicated(subset='user')]['user'].values)
    user_df1 = df[df['user'].map(lambda x: x in user)]
    user_df2 = df[df['user'].map(lambda x: x not in user)]
    rating_avg = user_df1.groupby('user').mean()
    rating_avg = rating_avg.rename(columns={'rating':'rating_avg'})
    rating_avg.reset_index(inplace=True)
    new_df1 = pd.merge(user_df1, rating_avg)
    new_df1.drop(['rating'], axis=1, inplace=True)
    new_df1 = new_df1.rename(columns={'rating_avg':'rating'})
    new_df1.drop_duplicates(subset='user', inplace=True)
    new_df = pd.concat([new_df1, user_df2])
    rating_book2_seoul = pd.concat([rating_book2_seoul, new_df])

In [ ]:
rating_book2_seoul

                user         book  book_ID  rating
0      8BRvenGmn56VJ  젊은 베르테르의 슬픔  b4Q5ZB4    4.50
2      YaR5YV8lyxgX1  젊은 베르테르의 슬픔  bogqOd1    3.75
4      8nPvyGlM4xYo0  젊은 베르테르의 슬픔  bogqOd1    3.50
7      RE952bOaZ5Q72  젊은 베르테르의 슬픔  b4Q5ZB4    3.50
9      YMKqmEORkqloD  젊은 베르테르의 슬픔  b4Q5ZB4    2.25
...              ...          ...      ...     ...
33503  RE952nyEZ5Q72       자기만의 방  bovdKxP    3.50
33533  2mwvgaoMgxMa7       자기만의 방  bovdKxP    4.50
33606  WwRqoggDDqlzB       자기만의 방  bovdKxP    4.50
34062  g64qzYYdWxER0       자기만의 방  bovdKxP    3.50
34927  4WLxZNL1rxroA       자기만의 방  bovdKxP    4.00

[4738 rows x 4 columns]

In [ ]:
no_dup_seoul = seoul_list[seoul_list['book'].map(lambda x: x not in dup_book_seoul)]
no_dup_seoul

                user           book  book_ID  rating
0      8nPvyyWmovYo0  해리 포터와 마법사의 돌  boYDGk4     3.0
1      8nPvyyWmovYo0           파리대왕  bowNK14     3.5
2      8nPvyyWmovYo0        지금 이 순간  boYOaR9     2.5
3      DgwxAeQYNxrMj     느리게 걷는 즐거움  b9R8Aam     3.5
4      DgwxAeQYNxrMj         칠드런 액트  byEjdj9     4.0
...              ...            ...      ...     ...
35412  17ovVzDWLvzyn       살인자의 기억법  b4el5q9     4.0
35415  17ovVzDWLvzyn           제3인류  b40OPK9     3.0
35416  17ovVzDWLvzyn       양과 강철의 숲  bop10Py     3.5
35418  17ovVzDWLvzyn  해리 포터와 마법사의 돌  boYDGk4     4.0
35420  17ovVzDWLvzyn    나의 라임 오렌지나무  byzeJko     5.0

[27881 rows x 4 columns]

In [ ]:
new_book_rating_seoul = pd.concat([no_dup_seoul, rating_book1_seoul, rating_book2_seoul]);
new_book_rating_seoul.reset_index(drop=True, inplace=True)
new_book_rating_seoul

                user           book  book_ID  rating
0      8nPvyyWmovYo0  해리 포터와 마법사의 돌  boYDGk4     3.0
1      8nPvyyWmovYo0           파리대왕  bowNK14     3.5
2      8nPvyyWmovYo0        지금 이 순간  boYOaR9     2.5
3      DgwxAeQYNxrMj     느리게 걷는 즐거움  b9R8Aam     3.5
4      DgwxAeQYNxrMj         칠드런 액트  byEjdj9     4.0
...              ...            ...      ...     ...
34564  RE952nyEZ5Q72         자기만의 방  bovdKxP     3.5
34565  2mwvgaoMgxMa7         자기만의 방  bovdKxP     4.5
34566  WwRqoggDDqlzB         자기만의 방  bovdKxP     4.5
34567  g64qzYYdWxER0         자기만의 방  bovdKxP     3.5
34568  4WLxZNL1rxroA         자기만의 방  bovdKxP     4.0

[34569 rows x 4 columns]

In [ ]:
new_book_rating_seoul.pivot('user','book','rating')

book,0시를 향하여,100 인생 그림책,11분,1219 끝이 시작이다,13계단,13층 나무 집,19호실로 가다,1Q84,1차원이 되고 싶어,2016 제7회 젊은작가상 수상작품집,...,환상통,환야,환한 숨,황석영의 밥도둑,후와후와,흉가,흑뢰성,희랍어 시간,희망장,희지의 세계
user,,,,,,,,,,,,,,,,,,,,,
06nkPvrlxgarB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0LzNM5Nox26j7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV0Qrlxzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV1aGrqzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV1kA2qzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zNM5Nyk9Gv26j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzQDn526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
zNM5NzbLo526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzddl526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzlkd526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 전처리 완료한 교보, 서울/베스트셀러 합치기

In [ ]:
kyobo_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면,김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽 The One Thing,게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791161571188,불편한 편의점,김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
3,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
4,9788936438838,아버지의 해방일지,정지아,소설,NaN,"새삼스럽게 경탄스럽다!\n압도적인 몰입감, 가슴 먹먹한 감동\n정지아의 손끝에서 펼..."
...,...,...,...,...,...,...
513,9791192227481,12 1/2 부와 성공을 부르는 12가지 원칙,게리 바이너척,자기계발,NaN,“출판업계 최초 24시간 만에 100만 부 팔린 책”\n뉴욕타임스 베스트셀러 작가 ...
514,9791162542569,하루를 48시간으로 사는 마법,이재은,자기계발,NaN,“무심코 허비했던 당신의 하루를 되돌려드립니다!”\n‘방송국 헤르미온느’ 이재은 아...
515,9788972773641,호감 가는 말투에는 비밀이 있다,장신웨,자기계발,NaN,오해는 줄이고 이해는 높이는 말하기를 배우다!\n중국의 최대 포털 사이트 바이두의 ...
516,9791165345204,책들의 부엌,김지혜,소설,NaN,★★★ 《책들의 부엌》 50쇄 기념 인사이드 에디션 출간 ★★★\n일상에서 벗어나고...
517,9788931011623,사랑의 기술,에리히 프롬,인문,NaN,에리히 프롬의 마지막을 함께한 라이너 풍크 박사의 \n《사랑의 기술》 50주년 기념...

In [ ]:
seoul_sel

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9788949162126,달콩이네 떡집,김리리,NaN,8.0,80만 부 돌파!\n초등 3학년 국어 교과서 수록 \n「만복이네 떡집」 시리즈 최신...
1,9788954681155,홍학의 자리,정해연,NaN,8.0,“이 행복이 영원할 거라고 생각한 적은 없었다.\n그러나 이런 끝을 상상한 적도 없...
2,9788997962129,망원동 브라더스,김호연,NaN,8.0,"상처받은 이들이여, 연체된 인생들이 모여 사는 8평 옥탑방으로 오라!\n\n김호연의..."
3,9788925588735,프로젝트 헤일메리,앤디 위어,NaN,8.0,“이름도 기억 못하는 내가 인류의 희망이라니?”\n멸망 위기의 지구 구하기 프로젝트...
4,9788954677158,긴긴밤,루리,NaN,8.0,제21회 문학동네어린이문학상 대상 수상작 『긴긴밤』\n\n세상에 마지막 하나 남은 ...
...,...,...,...,...,...,...
849,9791192097060,소마,채사장,NaN,8.0,"※양장본 리커버 에디션: 매장 구매, 바로드림 구매 시에는 일반판 랜덤으로 제공됩니..."
850,9791159257100,얼음 속의 엄마를 떠나보내다,남유하,NaN,8.0,한낙원과학소설상 수상ㆍ과학소재공모전 우수상에 수상 빛나는 작가. 남유하의 판타지 고...
851,9791189336462,헌책방 기담 수집가,윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
852,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
853,9791159257117,클락워크 도깨비,황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...

In [ ]:
final_book = pd.concat([kyobo_sel, seoul_sel])
final_book.reset_index(drop=True, inplace=True)
final_book

,상품코드,상품명,인물,분야,분류기호,책 소개
0,9791190538510,만일 내가 인생을 다시 산다면,김혜남,인문,NaN,“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그...
1,9788997575169,원씽 The One Thing,게리 켈러 외,자기계발,NaN,전 세계에서 두 번째로 큰 투자개발 회사의 대표이자 전미 130만 부 이상이 팔린 ...
2,9791161571188,불편한 편의점,김호연,소설,NaN,"원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!..."
3,9791191043297,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",이치조 미사키,소설,NaN,"제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중..."
4,9788936438838,아버지의 해방일지,정지아,소설,NaN,"새삼스럽게 경탄스럽다!\n압도적인 몰입감, 가슴 먹먹한 감동\n정지아의 손끝에서 펼..."
...,...,...,...,...,...,...
1312,9791192097060,소마,채사장,NaN,8.0,"※양장본 리커버 에디션: 매장 구매, 바로드림 구매 시에는 일반판 랜덤으로 제공됩니..."
1313,9791159257100,얼음 속의 엄마를 떠나보내다,남유하,NaN,8.0,한낙원과학소설상 수상ㆍ과학소재공모전 우수상에 수상 빛나는 작가. 남유하의 판타지 고...
1314,9791189336462,헌책방 기담 수집가,윤성근,NaN,8.0,사연 있는 책을 찾아드립니다 \n수수료는 당신 삶의 이야기!\n\n감동과 미스터리가...
1315,9791159257094,세상 끝 아파트에서 유령을 만나는 법,정지윤,NaN,8.0,"증강현실이 간판과 길거리 공연, 실시간 뉴스까지 눈앞에 바로 제공해주는 확장현실로 ..."
1316,9791159257117,클락워크 도깨비,황모과,NaN,8.0,한국과학문학상 대상· 2021 SF어워드 수상 작가 황모과.. 주목받는 SF작가가 ...

In [ ]:
# 상품명 중복 책 없는지 마지막으로 확인
final_book[final_book.duplicated('상품명')]

Empty DataFrame
Columns: [상품코드, 상품명, 인물, 분야, 분류기호, 책 소개]
Index: []

In [ ]:
final_book.to_csv('추천도서목록_1317권.csv', index=False)

In [ ]:
new_book_rating

                user              book  book_ID  rating
0      DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
1      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
2      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
3      DgwxAeQYNxrMj       소크라테스 익스프레스  bo5qAzM     3.5
4      DgwxAeQYNxrMj        미드나잇 라이브러리  byzQq6k     2.0
...              ...               ...      ...     ...
33624  ZWpqM79XL5rkn          초역 니체의 말  byKxqj9     3.5
33625  VRZv4oEBZqr6y          초역 니체의 말  byKxqj9     3.5
33626  4WLxZd2K8vroA          초역 니체의 말  byKxqj9     4.0
33627  4WLxZAnOm5roA          초역 니체의 말  byKxqj9     5.0
33628  WwRqodNY2vlzB          초역 니체의 말  byKxqj9     3.5

[32048 rows x 4 columns]

In [ ]:
new_book_rating_seoul

                user           book  book_ID  rating
0      8nPvyyWmovYo0  해리 포터와 마법사의 돌  boYDGk4     3.0
1      8nPvyyWmovYo0           파리대왕  bowNK14     3.5
2      8nPvyyWmovYo0        지금 이 순간  boYOaR9     2.5
3      DgwxAeQYNxrMj     느리게 걷는 즐거움  b9R8Aam     3.5
4      DgwxAeQYNxrMj         칠드런 액트  byEjdj9     4.0
...              ...            ...      ...     ...
34564  RE952nyEZ5Q72         자기만의 방  bovdKxP     3.5
34565  2mwvgaoMgxMa7         자기만의 방  bovdKxP     4.5
34566  WwRqoggDDqlzB         자기만의 방  bovdKxP     4.5
34567  g64qzYYdWxER0         자기만의 방  bovdKxP     3.5
34568  4WLxZNL1rxroA         자기만의 방  bovdKxP     4.0

[34569 rows x 4 columns]

In [ ]:
final_rating = pd.concat([new_book_rating, new_book_rating_seoul])
final_rating.reset_index(drop=True, inplace=True)
final_rating

                user              book  book_ID  rating
0      DgwxAeQYNxrMj     물고기는 존재하지 않는다  byLKj8M     5.0
1      DgwxAeQYNxrMj  21세기를 위한 21가지 제언  bo50Jrl     4.0
2      DgwxAeQYNxrMj               파친코  b9RlDAY     3.5
3      DgwxAeQYNxrMj       소크라테스 익스프레스  bo5qAzM     3.5
4      DgwxAeQYNxrMj        미드나잇 라이브러리  byzQq6k     2.0
...              ...               ...      ...     ...
66612  RE952nyEZ5Q72            자기만의 방  bovdKxP     3.5
66613  2mwvgaoMgxMa7            자기만의 방  bovdKxP     4.5
66614  WwRqoggDDqlzB            자기만의 방  bovdKxP     4.5
66615  g64qzYYdWxER0            자기만의 방  bovdKxP     3.5
66616  4WLxZNL1rxroA            자기만의 방  bovdKxP     4.0

[66617 rows x 4 columns]

In [ ]:
# user, book 중복 없는지 마지막으로 확인
final_rating.pivot('user','book','rating')

book,0시를 향하여,100 인생 그림책,100세 철학자의 행복론,10배의 법칙,11문자 살인사건,11분,12 1/2 부와 성공을 부르는 12가지 원칙,1219 끝이 시작이다,13계단,13층 나무 집,...,효기심의 권력으로 읽는 세계사 : 유럽 편,후와후와,휴먼카인드,흉가,흑뢰성,희랍어 시간,희망의 끈,희망장,희지의 세계,흰
user,,,,,,,,,,,,,,,,,,,,,
06nkPvrlxgarB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0LzNM5Nox26j7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV0Qrlxzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17ovV1aGrqzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
17ovV1kA2qzyn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zNM5Nynjnv26j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5NzQDn526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
zNM5NzbLo526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzddl526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zNM5Nzlkd526j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_rating.to_csv('사용자_도서_평점.csv', index=False)